### ISSUE TITLE
add a feature to make bar can stay at one line instead always newline

### ISSUE THREAD

**Issue by NewUserHa** [tqdm/tqdm#662] opened 2019-01-24 14:21 UTC
4.29.1
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] win32
ipython

I have some info needs to be logged and printed. but tqdm will case:
```
from tqdm import tqdm
import time
for _ in tqdm(range(2)):
  print('a')
  time.sleep(0.5)

  0%|                                                                                            | 0/2 [00:00<?, ?it/s]a
 50%|██████████████████████████████████████████                                          | 1/2 [00:00<00:00,  1.99it/s]a
100%|█████████████████████████████████████████████████████████ ███████████████████████████| 2/2 [00:01<00:00,  1.99it/s]

```
use tqdm.write:
```
from tqdm import tqdm
import time
for _ in tqdm(range(2)):
  tqdm.write('a')
  time.sleep(0.5)

a
 50%|██████████████████████████████████████████                               
a
 50%|██████████████████████████████████████████                               
100%|█████████████████████████████████████████████████████████ ███████████████████████████| 2/2 [00:01<00:00,  1.99it/s]
```

is there a way to archeve:
```
a
a
 50%|██████████████████████████████████████████                               
100%|█████████████████████████████████████████████████████████ ███████████████████████████| 2/2 [00:01<00:00,  1.99it/s]
```
or even make there's only one bar last?
thanks

**Comment by casperdcl** [comment] 2019-01-24 17:52
looks like a windows issue #556, #200, #499, #454, #307...

you can try replacing `tqdm(range(2))` -> `tqdm(range(2), ascii=True)`

**Comment by casperdcl** [comment] 2019-01-24 17:53
also try installing `colorama`

**Comment by NewUserHa** [comment] 2019-01-25 03:10
`Requirement already satisfied: colorama in c:\program files\python37\lib\site-packages (0.3.9)`
```
from tqdm import tqdm
import time
for _ in tqdm(range(2), ascii=True):
  print('a')
  time.sleep(0.5)
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]a
 50%|##########################################                                          | 1/2 [00:00<00:00,  1.99it/s]a
100%|####################################################################################| 2/2 [00:01<00:00,  1.99it/s]

```

**Comment by NewUserHa** [comment] 2019-01-25 03:40
![image](https://user-images.githubusercontent.com/32261870/51723910-dce93e00-2095-11e9-9043-7a46611d75b6.png)
I haven't resized the window after opening

**Comment by casperdcl** [comment] 2019-01-25 10:58
if you manually set `ncols=80` or similar, do you still get this issue?

**Comment by NewUserHa** [comment] 2019-01-25 12:32
![image](https://user-images.githubusercontent.com/32261870/51746133-18105f00-20e0-11e9-9f2d-c0a6441ebdf2.png)
NO

**Comment by casperdcl** [comment] 2019-01-25 21:23
does this fix your issue?

```
pip install -e git+https://github.com/tqdm/tqdm.git@win_fix#egg=tqdm
```

and then

```python
from tqdm import tqdm
import time
for _ in tqdm(range(2)):
  tqdm.write('a')
  time.sleep(0.5)
```

**Comment by NewUserHa** [comment] 2019-01-26 04:03
![image](https://user-images.githubusercontent.com/32261870/51782391-4df62780-2162-11e9-9d6c-4f8244ef6cb0.png)

**Comment by NewUserHa** [comment] 2019-01-26 04:04
![image](https://user-images.githubusercontent.com/32261870/51782405-8ac21e80-2162-11e9-960c-68aea2021a95.png)

**Comment by NewUserHa** [comment] 2019-01-27 03:46
winfix:
![image](https://user-images.githubusercontent.com/32261870/51796196-91b36480-2228-11e9-8697-895a79fdbf54.png)

master just installed few second ago:
![image](https://user-images.githubusercontent.com/32261870/51796216-df2fd180-2228-11e9-9668-6b1070b63b1d.png)
master also work for cmd and powershell. (but didn't do test with winfix.)

**Comment by NewUserHa** [comment] 2019-01-27 04:32
master:
![image](https://user-images.githubusercontent.com/32261870/51796492-38026880-222f-11e9-9bdd-454b4202baf7.png)
can consider reduce default ncols detected on windows and fix above too?

can also fix the behavior with default `print` function?

**Comment by casperdcl** [comment] 2019-05-09 16:45
duplicate of #454 #499 #556

**Closed by casperdcl** 2019-05-09 16:45 UTC
Labels: question

**Comment by matu1003** [comment] 2019-06-13 18:22
Try doing this:
from tqdm import tqdm_notebook
import time
for _ in tqdm(range(2)):
      print(‘a’)
      time.sleep(0.5)

**Comment by NewUserHa** [comment] 2019-10-09 12:45
what about make `ascii` and `ncols` default used on windows to avoid this issue at the beginning? @casperdcl

**Comment by casperdcl** [comment] 2019-10-09 13:49
yes, part of #815...

**Comment by NewUserHa** [comment] 2019-10-09 13:53
thanks!
