### ISSUE TITLE
Tqdm notebook / trange prints nothing in Google Colab local runtime

### ISSUE THREAD

**Issue by rnett** [tqdm/tqdm#687] opened 2019-03-02 08:35 UTC
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

This is using the jupyter notebook support.

I have been trying to use the progress bar in Google Colab.  It works fine when using the hosted runtime.

However, when I use a local time, nothing is shown at all.

To make things even weirder, it works just fine in jupyterlab on the local runtime, just not in Colab when using the local runtime.

For the hosted runtime:
Tqdm: 4.28.1
Python: 3.6.7
OS: [GCC 8.2.0] linux

For the local runtime:
Tqdm: 4.31.1
Python: 3.5.3
OS: [GCC 6.3.0 20170516] linux

Example:
```python
from tqdm import tnrange as trange
from time import sleep

for i in trange(10):
  sleep(1)
```

Google Colab, Hosted Runtime: works
Google Colab, Local Runtime: fails, shows nothing
Jupyter Lab, Local Runtime: works

**Comment by casperdcl** [comment] 2019-03-04 01:07
duplicate of #558

**Comment by rnett** [comment] 2019-03-04 04:08
#640 does not help.  I suspect its a separate issue or a versioning issue as it runs fine in hosted colab and local jupyterlab, just not local colab.

**Comment by chengs** [comment] 2019-03-29 06:47
Yes, #640 is not designed for this issue. 

@rnett You seems to use local jupyter as a backend of Colab. I understand this but don't see the reason: can't you just use jupyter-labl locally?

This issue is hard to fix. Ipython budgets will register a JavaScript script in the Jupyter to show all the progress bar. Apparently, the JavaScript script cannot be registered into Colab frontend.

**Comment by chengs** [comment] 2019-04-10 12:34
@casperdcl I close this due to my investigation above.

**Closed by chengs** 2019-04-10 12:34 UTC
Labels: bug-warning, question, submodule-notebook, wont-fix

**Comment by pharringtonp19** [comment] 2020-11-18 13:03
Any updates on this issue?
