### ISSUE TITLE
Notebook nested progress bar introduces blank lines when leave is set to `False`

### ISSUE THREAD

**Issue by hadim** [tqdm/tqdm#693] opened 2019-03-05 16:18 UTC
Notebook nested progress bar introduces blank lines when leave is set to `False`

Here is a gif showing the issue:

![screencast](https://user-images.githubusercontent.com/528003/53819657-5814fe00-3f38-11e9-8256-f76b7e8ab8f4.gif)

Is that normal or am I doing something wrong?

**Comment by casperdcl** [comment] 2019-03-06 22:19
Hey @hadim - this is a duplicate of #433 (upstream issue with jupyter)

**Closed** 2019-03-06 22:20 UTC
Labels: duplicate, invalid, submodule-notebook

**Comment by hadim** [comment] 2019-03-06 22:21
Thanks for the information!

**Comment by matbun** [comment] 2022-01-25 15:35
I have noticed a similar uwanted behavior with ipywidgets 7.6.5. Basically, when the inner bar is removed, it leaves an empty blank line in the output of a cell, which is rather annoying if the outer loop performs many iterations.

To reproduce:

```
from tqdm.notebook import tqdm
import time

episodes_pbar = tqdm(range(10), total=10, leave=True)
episodes_pbar.set_description("Episodes")

for ep in episodes_pbar:
    iters_pbar = tqdm(range(10), total=10, leave=False)
    for i in iters_pbar:
        time.sleep(0.1)
```
