### ISSUE TITLE
[feature request] force plain ASCII display of tqdm.autonotebook within a submodule

### ISSUE THREAD

**Issue by DSLituiev** [tqdm/tqdm#1035] opened 2020-09-14 23:12 UTC
I am using a module that obviously calls `tqdm.autonotebook` internally.
Everything is fine untill I re-load a notebook, and then I see [this `HBox...` thing](https://github.com/tqdm/tqdm/issues/394#issuecomment-384743637) (though I am using `:8888/tree` / plain Jupyter).

My question or request is: How can one disable the auto-notebook widget mode using a global switch? I.e. something like `tqdm.autonotebook.ascii()` 

System info:
```
4.43.0 3.7.2 | packaged by conda-forge | (default, Mar 19 2019, 20:46:22) 
[Clang 4.0.1 (tags/RELEASE_401/final)] darwin
```

**Comment by casperdcl** [comment] 2020-09-15 00:34
I think this is essentially a duplicate of #937

**Comment by DSLituiev** [comment] 2020-09-15 16:30
I don't quite think so. The issue might be related, but I don't see a clear
request for a global flag in the above issue.

**Comment by casperdcl** [comment] 2020-09-15 17:38
ah you mean you want to pass in different initialiser arguments to an external module which is using `tqdm`? That would be #614...

**Closed** 2020-11-09 22:39 UTC
Labels: duplicate 🗐, question/docs ‽, submodule ⊂
