### ISSUE TITLE
Line spacing before/after progressbar in Jupyter Notebook

### ISSUE THREAD

**Issue by peidaqi** [tqdm/tqdm#870] opened 2019-12-22 19:36 UTC
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
4.41.0 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] linux
Jupyter notebook: The version of the notebook server is: 6.0.2
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

The line spacing before/after the progressbar in jupyter notebook seems to be much larger than normal text:
![image](https://user-images.githubusercontent.com/18495787/71326399-78627900-24c8-11ea-8c92-42abc8aed3ef.png)

Anyway to fix this?

**Comment by casperdcl** [comment] 2019-12-26 12:23
seems to be a duplicate of #433

**Comment by casperdcl** [comment] 2022-03-26 19:23
This has been reported before (originally at #433) - the real problem is upstream https://github.com/jupyterlab/jupyterlab/issues/7354 (bot auto-closed, should be re-opened) and https://github.com/jupyter-widgets/ipywidgets/issues/1845.

**Closed by casperdcl** 2022-03-26 19:23 UTC
Labels: duplicate 🗐, invalid ⛔, p2-bug-warning ⚠, submodule-notebook 📓
