### ISSUE TITLE
Tqdm Zip()

### ISSUE THREAD

**Issue by prdai** [tqdm/tqdm#1256] opened 2021-10-08 04:58 UTC
Tqdm Zip()

When I run tqdm with a zip function it gives an output like
10000it [00:00, 2294226.01it/s]

but if there is no zip function
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 2671531.21it/s]

I think having the same progress bar as the no zip function will be really useful because in it I can see the max num and I can see a progress bar I think this would be really useful.

Just an idea.

With best Regards.

**Comment by tloki** [comment] 2021-10-14 13:49
Same as #1261 

This has nothing to do with tqdm, and all to do with `zip` function, which is by design. But just to fix your problem, I'll try to show you by example:

this won't show progress bar since zip does not have `__len__` method.
`for e1, e2 in tqdm.tqdm(zip(some_iterable1, some_iterable2))`

but this will work:
`for e1, e2 in zip(tqdm.tqdm(some_iterable1), some_iterable2)`
if `some_iterable1` "has length" (has `__len__` implemented)

please close the issue, since it's not tqdm issue

**Closed as completed** 2021-10-14 13:57 UTC
Labels: question/docs ‽
