### ISSUE TITLE
Failing in notebook

### ISSUE THREAD

**Issue by grburgess** [tqdm/tqdm#1359] opened 2022-08-25 04:33 UTC
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
 ```
4.64.0 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)] darwin
 ```

Upon switching to an Apple M1 chip, I have been unable to get the progress bars to work in the notebook.
It is possible I have not installed something correctly.

JupyterLab configuration:

```
JupyterLab v3.4.5
Other labextensions (built into JupyterLab)
   app dir: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab
        @aquirdturtle/collapsible_headings v3.0.0 enabled OK
        @jlab-enhanced/cell-toolbar v3.5.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.2 enabled OK
        @timkpaine/jupyterlab_miami_nights v0.3.1 enabled OK
        @yudai-nkt/jupyterlab_city-lights-theme v3.0.0 enabled OK
        js v0.1.0 enabled OK
        jupyter-matplotlib v0.11.2 enabled OK
        jupyterlab-code-snippets v2.1.0 enabled OK
        jupyterlab-jupytext v1.3.8 enabled OK
        jupyterlab-theme-hale v0.1.3 enabled OK

```

While everything works fine in the shell, when I run something in the notebookI get this:

```python
from tqdm.notebook import tqdm

for i in tqdm(range(10)):
    
    pass
```

```
root:
    n: 0
    total: 10
    elapsed: 0.021565914154052734
    ncols: null
    nrows: 84
    prefix: ""
    ascii: false
    unit: "it"
    unit_scale: false
    rate: null
    bar_format: null
    postfix: null
    unit_divisor: 1000
    initial: 0
    colour: null
```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by teristam** [comment] 2022-08-26 12:50
I have the same error and I am just on a Windows machine. I am also on Jupyterlab 3.4.5

**Comment by tarrade** [comment] 2022-08-26 13:25
same error on Ubuntu 20.04 also using Jupyterlab 3.4.5 and recent packages.

**Comment by parashardhapola** [comment] 2022-08-26 14:15
Same issue. Some of the relevant (IMHO) installed packages:

```
anyio==3.6.1
ipykernel==6.15.1
ipython==8.4.0
ipython-autotime==0.3.1
ipython-genutils==0.2.0
ipywidgets==8.0.1
jedi==0.18.1
Jinja2==3.1.2
joblib==1.1.0
json5==0.9.10
jsonschema==4.14.0
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyter_client==7.3.5
jupyterlab==3.4.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.2
jupyterlab_server==2.15.1
jupytext==1.14.1
markdown-it-py==2.1.0
MarkupSafe==2.1.1
msgpack==1.0.4
multipledispatch==0.6.0
nbclassic==0.4.3
nbclient==0.6.7
nbconvert==7.0.0
nbformat==5.4.0
notebook==6.4.12
notebook-shim==0.1.0
pandocfilters==1.5.0
prometheus-client==0.14.1
prompt-toolkit==3.0.30
ptyprocess==0.7.0
pyzmq==23.2.1
toolz==0.12.0
tornado==6.2
websocket-client==1.4.0
widgetsnbextension==4.0.2
```

**Comment by lukasbindreiter** [comment] 2022-08-29 08:54
Apparently with the new version of `ipywidgets` the `_repr_json_` method of `TqdmHBox` is favored instead of the widget display (https://github.com/tqdm/tqdm/blob/master/tqdm/notebook.py#L79)

So a temporary workaround is to replace `TqdmHBox` with a version that just doesn't have `_repr_json_`. Executing this cell fixes the issue for the current ipython session.

```python
# hack: execute this cell to fix tqdm progress bar
from ipywidgets import HBox
import tqdm.notebook

class TqdmHBox(HBox):
    def __repr__(self, pretty=False):
        pbar = getattr(self, 'pbar', None)
        if pbar is None:
            return super(TqdmHBox, self).__repr__()
        return pbar.format_meter(**pbar.format_dict)

tqdm.notebook.TqdmHBox = TqdmHBox
```

**Comment by casperdcl** [comment] 2022-08-30 17:02
- `jupyter notebook` works fine; I believe you mean `jupyter lab` is broken
  + ergo closing duplicate of #1310

Happy to re-open if different.

**Closed by casperdcl** 2022-08-30 17:02 UTC
Labels: duplicate 🗐, p2-bug-warning ⚠, submodule-notebook 📓

**Comment by jasonkhadka** [comment] 2023-01-04 13:52
I still have the problem on jupyter notebook with  `tqdm-4.64.1` and `ipywidgets-8.0.4`. 
The problem goes away if I reinstall `ipywidgets-7.0.0`. So, I do not think is issue is resolved at the moment.
@casperdcl

**Comment by alexnkorovin** [comment] 2023-04-14 13:28
from tqdm.notebook import tqdm
for i in tqdm(range(10):
    pass

Led to error in output: Error displaying widget: model not found
import "from tqdm import tqdm" worked but as error print:

Downgrading helped:
ipywidgets                             8.0.6-pyhd8ed1ab_0 --> 7.7.5-pyhd8ed1ab_0 
jupyterlab_widgets                     3.0.7-pyhd8ed1ab_0 --> 1.1.4-pyhd8ed1ab_0 
widgetsnbextension                     4.0.7-pyhd8ed1ab_0 --> 3.6.4-pyhd8ed1ab_0
