### ISSUE TITLE
Notebook progressbar stalls on `lock.acquire()`.

### ISSUE THREAD

**Issue by tsbertalan** [tqdm/tqdm#461] opened 2017-10-04 13:42 UTC
When used in in a notebook that makes heavy use of tqdm and the line magic `%timeit`, my progressbars eventually stop updating. Keyboard interrupt gives the (long) traceback at the end of this message. To proceed with the notebook, I need to refrain from using any more progress bars (`tqdm.tqdm` or `tqdm.tqdm_notebook`).

The bar is effectively called as `for x in tqdm_notebook(range(n), desc='hello'):`.

If I attempt and then interrupt the cell a few times, I might eventually get this output, which I believe is cached and flushed from a previous run:
```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/tsbertalan/venv3/lib/python3.5/site-packages/tqdm/_tqdm.py", line 890, in __del__
    self.close()
  File "/home/tsbertalan/venv3/lib/python3.5/site-packages/tqdm/_tqdm_notebook.py", line 210, in close
    super(tqdm_notebook, self).close(*args, **kwargs)
  File "/home/tsbertalan/venv3/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1118, in close
    if self.disable:
AttributeError: 'tqdm_notebook' object has no attribute 'disable'
```

I have tqdm version 4.18.0, Jupyter 1.0.0, and Ipython 6.1.0; and `sys.version_info` is `sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)`. This is on Ubuntu 16.04.

Unfortunately, I can't seem to write an minimal failing example; this is only showing up in my big complicated notebook. This code does not use any file io, multithreading, or multiprocessing (yet), though it does make heavy use of `scipy.optimize.*`, which I suppose might implicitly use some of these things for some wrapped executables or something.

I am able to open a `%debug` prompt after the `KeyboardInterrupt` to investigate any ideas you might have.

The actual `KeyboardInterrupt` trace is this:
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-54-f21a3ba5ad44> in <module>()
      1 ivpPreconditioner = IVPpreconditioner(smap, nrepeat=2, pbar=dict(notebook=True))
----> 2 get_ipython().magic('timeit -r1 -n1 preconditioned.append(ivpPreconditioner(preconditioned[-1]))')
      3 show(preconditioned[-1], label='\n(IVP preconditioned)');

~/venv3/lib/python3.5/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2144         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2145         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2146         return self.run_line_magic(magic_name, magic_arg_s)
   2147 
   2148     #-------------------------------------------------------------------------

~/venv3/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2065                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2066             with self.builtin_trap:
-> 2067                 result = fn(*args,**kwargs)
   2068             return result
   2069 

<decorator-gen-61> in timeit(self, line, cell)

~/venv3/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/venv3/lib/python3.5/site-packages/IPython/core/magics/execution.py in timeit(self, line, cell)
   1082                     break
   1083 
-> 1084         all_runs = timer.repeat(repeat, number)
   1085         best = min(all_runs) / number
   1086         worst = max(all_runs) / number

/usr/lib/python3.5/timeit.py in repeat(self, repeat, number)
    204         r = []
    205         for i in range(repeat):
--> 206             t = self.timeit(number)
    207             r.append(t)
    208         return r

~/venv3/lib/python3.5/site-packages/IPython/core/magics/execution.py in timeit(self, number)
    158         gc.disable()
    159         try:
--> 160             timing = self.inner(it, self.timer)
    161         finally:
    162             if gcold:

<magic-timeit> in inner(_it, _timer)

<ipython-input-50-49457f06446b> in __call__(self, x)
     50             nrepeat = 1
     51         nrepeat += 1
---> 52         steps = self.step(x, nrepeat)
     53         o1 = self.objective(steps[0], steps[1])
     54         o2 = self.objective(steps[-2], steps[-1])

<ipython-input-50-49457f06446b> in step(self, x, nrepeat)
     27 
     28         if nrepeat > 1:
---> 29             ite = self.pbar(range(self.nrepeat))
     30         else:
     31             ite = range(self.nrepeat)

~/Dropbox/Projects/Circadian Rhythms/src/circadian/procPool.py in __call__(self, *args, **prioritizedKwargs)
    291             })
    292         kwargs.update(prioritizedKwargs)
--> 293         return self.f(*args, **kwargs)
    294 
    295     def __bool__(self):

~/venv3/lib/python3.5/site-packages/tqdm/__init__.py in tqdm_notebook(*args, **kwargs)
     17     """See tqdm._tqdm_notebook.tqdm_notebook for full documentation"""
     18     from ._tqdm_notebook import tqdm_notebook as _tqdm_notebook
---> 19     return _tqdm_notebook(*args, **kwargs)
     20 
     21 

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm.py in __new__(cls, *args, **kwargs)
    445         if "_instances" not in cls.__dict__:
    446             cls._instances = WeakSet()
--> 447         with cls._lock:
    448             cls._instances.add(instance)
    449         # Create the monitoring thread

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm.py in __enter__(self)
     75 
     76     def __enter__(self):
---> 77         self.acquire()
     78 
     79     def __exit__(self, *exc):

~/venv3/lib/python3.5/site-packages/tqdm/_tqdm.py in acquire(self)
     68     def acquire(self):
     69         for lock in self.locks:
---> 70             lock.acquire()
     71 
     72     def release(self):

KeyboardInterrupt: 
```

**Comment by tsbertalan** [comment] 2017-10-04 13:58
Running that cell with its `%timeit` magic removed doesn't stop it from stalling. I'm rerunning the whole notebook without these now to see if it can get all the way through, but that might take an hour or two.

**Comment by tsbertalan** [comment] 2017-10-04 14:31
Well, I got there faster than expected. Even without the `%timeit`s, the progress bars eventually stall.

**Comment by casperdcl** [comment] 2017-10-04 15:03
does it stall with an earlier version pf `tqdm`? If so, perhaps it's your code and not the progress bar?

**Comment by MPagel** [comment] 2017-10-04 21:59
I'm having a similar problem.  I'll go back to PyPy tqdm to test, but right now it's stalling when trying to acquire a lock.

> Locals by frame, innermost last
> Frame external_write_mode in C:\Program Files\Python\27\lib\site-packages\tqdm\_tqdm.py at line 512
>         fp: <open file '<stderr>', mode 'w' at 0x000000000253B150>
>         file: <open file '<stderr>', mode 'w' at 0x000000000253B150>
>         nolock: False
>         cls: <class 'tqdm._tqdm.tqdm'>
> Frame acquire in C:\Program Files\Python\27\lib\site-packages\tqdm\_tqdm.py at line 70
>         lock: <Lock(owner=None)>
>         self: <tqdm._tqdm.TqdmDefaultWriteLock object at 0x0000000003F00E48>
>  Stack: | File "ReadQueues.py", line 1307, in <module>
>     main(sys.argv) | File "ReadQueues.py", line 1277, in main
>     pr.ts_eprint("STACKTRACE: \n{}".format(excPlus()),e=e,tb=True) | File "fns_print.py", line 159, in ts_eprint
>     pr(*args, **kwargs) | File "fns_print.py", line 102, in pr
>     pr_str = buildString(*args, **kwargs) | File "fns_print.py", line 76, in buildString
>     args.append(tracey(**kwargs)) | File "fns_print.py", line 57, in tracey
>     for line in traceback.format_stack():

**Comment by MPagel** [comment] 2017-10-04 22:25
confirmed.  I do not have the issue in 4.17.1 (the last that I can find completely pre-parallelism)

`pip install -I --force-reinstall --no-cache-dir -v -U https://github.com/tqdm/tqdm/releases/download/v4.17.1/tqdm-4.17.1-py2.py3-none-any.whl#egg=tqdm`

**Comment by casperdcl** [comment] 2017-10-04 22:32
Could this be related to #463?

**Comment by casperdcl** [comment] 2017-10-05 00:03
*EDIT* #463 is unrelated to #459, and #459 is a bug which should be fixed on `devel` branch now

**Comment by casperdcl** [comment] 2017-10-05 02:41
just to note, you should be able to disable locks by doing:

```python
from tqdm import tqdm
tqdm.get_lock().locks = []
```

which should fix things for now...

**Comment by tsbertalan** [comment] 2017-10-05 15:09
Downgrading with just
`pip install tqdm==4.17.1`
in the virtual environment in question seems to have fixed it for me.

**Comment by chengs** [comment] 2017-10-05 23:31
me too
has the same problem in 4.19.1.post1

**Comment by casperdcl** [comment] 2017-10-06 21:47
Well this is why we provide `tqdm.tqdm.get_lock()` and `set_lock()` so you may use your own lock objects. Alternatively use the line of code I suggested above to disable `tqdm` locking

**Comment by chengs** [comment] 2017-10-06 21:58
Thank you @casperdcl. I understand.

A dirty solution is here (https://gist.github.com/belltailjp/5253066638ec76d97b085172b51356b3)

Nevertheless, isn't a more elegant way to make *tqdm* process safe?

**Comment by casperdcl** [comment] 2017-10-06 22:00
Happy to accept a PR!

**Comment by casperdcl** [comment] 2017-10-06 23:14
tried to modify your example. don't get why the following works:

```python
import sys
import time
from tqdm import tqdm
import multiprocessing as mp


def worker(pbar, n):
    pbar.n = n.value
    # pbar.get_lock().locks.append(n.get_lock())
    # pbar.set_lock(n.get_lock())
    # pbar.update()
    with n.get_lock():
        pbar.update()
        n.value += 1


ar = list(range(100))
with tqdm(ar) as pbar:
    jobs = []
    n = mp.Value('i', 0)
    # pbar.get_lock().locks.append(n.get_lock())
    for t in ar:
        job = mp.Process(target=worker, args=(pbar, n))
        job.start()
        jobs.append(job)
    for job in jobs:
        job.join()
    print(pbar.n, n.value)
```

**Comment by chengs** [comment] 2017-10-08 09:29
@casperdcl Eh... I have no idea
The author of this example is a Japanese. He only explained in Japanese, which I don't know either.
http://daily.belltail.jp/?p=2389

**Comment by chengs** [comment] 2017-10-14 13:51
@casperdcl 

The Japanese solution uses shared memory instead of locks. In your modified code, n is shared by all workers. So n is operated as if there is only one process. But for pbar.n, the main process has a pbar.n = 0 when the pool is created, and pbar.n does not change in the main process. So at the end, it is still 0.

**Comment by ferrine** [comment] 2019-02-15 13:18
Looks like we face related issue to this in https://github.com/pymc-devs/pymc3/issues/3302

**Comment by EKami** [comment] 2019-03-25 11:45
I'm facing the same issue with tqdm v4.31.1 stable and Python 3.7 in Pycharm debugger (running the program without the debugger works fine) with this piece of code:
```
        with ProcessPoolExecutor(max_workers=num_process) as pool:
            futures = [pool.submit(*future) for future in futures]
            # Print out the progress as tasks complete
            for future in tqdm(as_completed(futures), total=len(futures),
                               desc="Transforming labels"):
                res = future.result()
                ret_slides.append(res)
```

Downgrading to `4.17.1` didn't help me solve the issue.

**Comment by chengs** [comment] 2021-11-17 02:01
looks this did not appear in 2 years. closed.

**Closed by chengs** 2021-11-17 02:01 UTC
Labels: synchronisation ⇶
