### ISSUE TITLE
Telegram "Too Many Requests" Error

### ISSUE THREAD

**Issue by Hagai** [tqdm/tqdm#1220] opened 2021-08-03 12:50 UTC
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
 == 
  ```python
  import tqdm, sys
  import platform
  import requests
  print(requests.__version__, tqdm.__version__, sys.version, sys.platform)
  print(platform.platform())
  ```
2.22.0 4.50.2 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] win32
Windows-10-10.0.19041-SP0

Issue can be reproduced by:
 == 
  ```python
  from tqdm.contrib.telegram import tqdm
  for j in range(40):
    for i in tqdm(range(5000), token=TELEGRAM_TOKEN, chat_id=CHAT_ID):
        time.sleep(0.001) 
  ```
The error I got was KeyError: 'result' resulted from
tqdm\contrib\telegram.py in __init__(self, token, chat_id)
self.message_id = res.json()['result']['message_id']

The content of res.json() was:
{'ok': False, 'error_code': 429, 'description': 'Too Many Requests: retry after 3', 'parameters': {'retry_after': 3}}

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment] 2021-08-03 14:17
duplicate of #1076 (see https://github.com/tqdm/tqdm/issues/1076#issuecomment-731147899)

**Closed** 2021-08-14 20:51 UTC
Labels: p0-bug-critical ☢, duplicate 🗐, question/docs ‽, to-fix ⌛, submodule ⊂, c1-quick 🕐
