### ISSUE TITLE
Do we need a `tenumerate` fucntion?

### ISSUE THREAD

**Issue by TezRomacH** [tqdm/tqdm#840] opened 2019-11-09 21:18 UTC
Hi! We use the tqdm in [Catalyst](https://github.com/catalyst-team/catalyst) a lot, thank you for this library.

My frequent case is to use `tqdm` together with `enumerate`. I keep forgetting in which order to pass what, according to this:
> Wrapping enumerated iterables: use enumerate(tqdm(...)) instead of tqdm(enumerate(...)). The same applies to numpy.ndenumerate. This is because enumerate functions tend to hide the length of iterables. tqdm does not.

My suggestion is very simple, lets add an analog of `trange`: `tenumerate` to the standard functions. I can contribute this, the logic is very simple: 
```python
def tenumerate(iterable, **kwargs):
    _enumerate = np.ndenumerate if isinstance(iterable, np.ndarray) else enumerate
    return _enumerate(tqdm(iterable, **kwargs))
```

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [x] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment] 2019-11-10 11:09
Duplicate of #225 but thanks for bumping

**Closed** 2019-11-10 11:10 UTC
Labels: duplicate, enhancement-future, question, submodule
