### ISSUE TITLE
Old progressbars stay visible after reconnecting to notebook kernel

### ISSUE THREAD

**Issue by aplavin** [tqdm/tqdm#238] opened 2016-08-15 20:49 UTC
When there is a long-running process with progressbar (`tqdm_notebook`) in Jupyter notebook sometimes the connection can be temporarily lost, or the notebook manually closed and then opened. After reconnecting to the kernel the progressbar current state is correctly updated at least after another iteration, but if there is a nested progressbar with `leave=False`, it doesn't get deleted. Actually, it stays at the same state as when disconnected, and another progressbar gets added instead of replacing it, which is a bit confusing especially after reconnecting several times.
If this can be fixed relatively easy (either deleting the old progressbar, or marking it as an error at least), it would be nice (not a deal-breaked of course).

**Comment by lrq3000** [comment] 2016-08-16 13:29
Hey @aplavin,

Yes I spotted this bug when fixing [another issue](https://github.com/tqdm/tqdm/issues/186#issuecomment-230365097) but the root is in ipywidgets saving process (indeed, the bar is already deleted when closed, but it can still reappear in certain circumstances as you described). I [reported the bug to ipywidgets team here](https://github.com/ipython/ipywidgets/issues/624), please upvote it to raise awareness!

**Comment by casperdcl** [comment] 2016-12-06 16:54
going to close this for now as it seems like it's an issue with ipywidgets rather than tqdm

**Closed by casperdcl** 2016-12-06 16:54 UTC
Labels: bug-warn, invalid

**Comment by lrq3000** [comment] 2016-12-06 18:06
Yes users reported on ipywidgets repo that normally the issue is fixed now. :)
