### ISSUE TITLE
Progress bar updates in new line with tqdm.pandas()

### ISSUE THREAD

**Issue by devanshuDesai** [tqdm/tqdm#874] opened 2019-12-29 07:11 UTC
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

```
4.40.0 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] darwin
```

<img width="975" alt="Screen Shot 2019-12-28 at 12 49 46 AM" src="https://user-images.githubusercontent.com/37163544/71553587-ff32bc80-29c6-11ea-9eeb-d367fe16e9c4.png">

This bug is especially weird since it tends to occur only when I re-run a given cell i.e. the progress bar behaves as expected when running a cell with `.progress_apply()` the first time, but if you run the cell again without making any changes then it creates a new line for every update in the progress bar. Also, note that this behavior is unique to `tqdm.pandas()` and I have not been able to replicate it with `tqdm_notebook()`

**Comment by casperdcl** [comment] 2019-12-30 11:45
Is this is `lab` or `notebook`?

**Comment by devanshuDesai** [comment] 2019-12-30 19:31
This behavior is for `notebook`. Haven't tested it with `lab`.

**Comment by louiszhang97** [comment] 2020-03-29 04:08
Happens to me as well.

**Comment by casperdcl** [comment] 2020-03-29 12:06
looks like a duplicate of #433, #479, #550

**Comment by casperdcl** [comment] 2020-03-29 12:09
Possibly #548 too

**Comment by devanshuDesai** [comment] 2020-03-30 04:41
I disagree that it is a duplicate issue. While the issues you referenced exhibit similar behavior, they are only observed with nested loops while this issue was caused by a simple function call without any nesting.

**Comment by casperdcl** [comment] 2020-03-30 10:24
The image you posted was the 110th cell run so it's probably #548 (a previous bar not closed properly)

You couldn't try using `from tqdm.auto import tqdm, trange` rather than `from tqdm.auto import tqdm, trange`... or wait for next release #929

**Comment by casperdcl** [comment] 2022-03-26 19:25
is this still an issue? Happy to reopoen if so.

**Closed by casperdcl** 2022-03-26 19:25 UTC
Labels: invalid ⛔, question/docs ‽, need-feedback 📢, p2-bug-warning ⚠, submodule-notebook 📓
