### ISSUE TITLE
audible progress bar (feature suggestion)

### ISSUE THREAD

**Issue by sellisd** [tqdm/tqdm#1077] opened 2020-11-20 12:37 UTC
I was wondering if it is possible to add an optional sound notification, perhaps some sort of audible or ferquency based progress or other notification.

Why:
- could help make CLIs more accessible
- for long running programs it is nice to get notified when they are done (I often run them in bash as `./mylongscript.sh;  notify-send "end" "done"`)

**Comment by casperdcl** [comment] 2020-11-20 12:44
Duplicate of #988

**Closed** 2020-11-20 12:45 UTC
Labels: duplicate 🗐, p3-enhancement 🔥
