### ISSUE TITLE
After using try/except method, the progress chart can not be refreshed in a single line.

### ISSUE THREAD

**Issue by shmilydy** [tqdm/tqdm#810] opened 2019-09-11 13:23 UTC
This is my code:
![图片](https://user-images.githubusercontent.com/52773927/64700748-10b88d00-d4da-11e9-9b85-e372a5fed8a1.png)

and problem reappears

**Comment by casperdcl** [comment] 2019-09-11 14:48
duplicate of #809

**Closed by casperdcl** 2019-09-11 14:48 UTC
