### ISSUE TITLE
The inner loop of nested bar start on a new line instead of the same level as previous loop

### ISSUE THREAD

**Issue by bbbbear** [tqdm/tqdm#908] opened 2020-03-05 21:33 UTC
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
    + [x] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

Hi,

I got some problem on using tqdm with nested loop on jupyterlab.
As I set `leave = False` on the inner loop, the bar disappears as expected but the new bar is created on another line instead of replacing the previous one.
Resulting in making lots of blank lines and spaces between progress bar.
The code and the result that I've tested are as below.

`import time
from tqdm.notebook import trange
for i in trange(0,10,position=0):
    for j in trange(0,10,leave =False,position=1):
        for k in trange(0,10,leave =False,position=2):
            time.sleep(0.1)`
![image](https://user-images.githubusercontent.com/16562620/76026432-532ac600-5f61-11ea-9c43-cf1da36a0ed1.png)

I also try to follow the example on the readme, but I got the same problem.
[https://github.com/tqdm/tqdm#nested-progress-bars](url)

Code on the example.
![image](https://user-images.githubusercontent.com/16562620/76027529-5e7ef100-5f63-11ea-86dd-ef7581dc2960.png)

My result.
![image](https://user-images.githubusercontent.com/16562620/76028067-63907000-5f64-11ea-9d88-f5f9f7aaff75.png)

Btw, thanks for making our life easier by implementing a wonderful tool. I really love it <3.

**Comment by MaxHeuillet** [comment] 2020-03-30 12:57
I have the same issue : when I use tqdm on a nested loop in creates new lines... :'( 
Thanks

**Comment by casperdcl** [comment] 2020-03-31 18:12
looks like duplicate of #870, #433. In particular; the upstream issue https://github.com/jupyterlab/jupyterlab/issues/7354

**Closed** 2020-03-31 18:36 UTC
Labels: bug-warning, duplicate, invalid, submodule-notebook
