### ISSUE TITLE
jitter in IPython notebook

### ISSUE THREAD

**Issue by kmike** [tqdm/tqdm#50] opened 2015-11-10 18:47 UTC
Hey,

This is how tqdm 2.2.4 looks in IPython notebook: http://www.youtube.com/watch?v=GjRHAmj_xfc

This is how it used to look in 1.0: http://www.youtube.com/watch?v=t7e6IEdEaTc

Red color is fine (we're using stderr now, and it makes sense), but I think text shouldn't jump by default, and progress bar looks untidy (it is not image compression artifact - there are vertical lines, and the last symbol doesn't have the same height as other symbols).

I also find old `elapsed: ... left: ...` to be easier to understand than new `...<...`, but that's a personal preference :)

Code:

```py
import time
import random
from tqdm import tqdm

x = range(343)

for el in tqdm(x, "Loading", mininterval=0, leave=True):
    time.sleep(random.random() * 0.01)
```

**Comment by lrq3000** [comment] 2015-11-10 19:29
Hey @kmike, what version of IPython are you using? Did you try the latest Jupyter version?

I have tried on my Jupyter notebook, and there's no issue like the one we can saw on the video: the only moment the bar is momentarily jumpy is when the number go past a new magnitude (eg, 100 -> 1000), but this also happened before. On my notebook, the smooth (unicode) bar does progress correctly without causing any issue. Indeed the small blocks are also smaller in height and not only width, but they are centered vertically so that's fine (contrary to your install where they are not centered).

Here's a screenshot of what I see:
![jupyter-notebook-tqdm](https://cloud.githubusercontent.com/assets/1118942/11073179/a6b1b0a8-87e9-11e5-9e71-0bb0af5dd630.png)

Also, you can probably get the same result as tqdm v1.0 by setting ascii=False, since I guess the issue is in the management of unicode characters in your IPython install.

**Comment by kmike** [comment] 2015-11-10 19:32
Yeah, I know `ascii` argument may fix it, but this doesn't look like a good default. 
I'm using latest Jupyter notebook, Python 3.4, Firefox 42.0, OS X. The issue is more visible with small `mininterval` values.

**Comment by lrq3000** [comment] 2015-11-10 19:42
@kmike : correct, I can confirm the issue when `mininterval=0` on Chrome browser, Windows 7. And I can confirm that `ascii=True` fix the issue just like with tqdm v1.0.

So it seems that a few blocks are doing weird things because of their size variation. Unluckily, I'm not sure we can correct that in an easy way. Maybe we should just remove those buggy blocks? The progress bar will be less smooth, but also less jumpy.

**Comment by kmike** [comment] 2015-11-10 19:46
@lrq3000 thanks for looking into it. Removing buggy blocks sounds good; I hope not all blocks are buggy.

**Comment by casperdcl** [comment] 2015-11-10 20:04
Basically there's an issue with fonts. The 8 different unicode block characters are meant to be the same height, but occasionally fonts have a bigger 'full block' than the rest. On android terminal emulator the full block actually is wider than a standard character so the progressbar gradually goes off screen slightly... idk if we should be changing tqdm default to ascii because unicode-ready systems sometimes lie about their support...

**Comment by casperdcl** [comment] 2015-11-10 20:04
It seems that it's the notebook, not tqdm, at fault.

**Comment by lrq3000** [comment] 2015-11-10 20:08
Yes @casperdcl what you're explaining is what I was deducting just now after running some tests in Jupyter :p
I'm not sure we should switch to ascii=True as default, since the issue isn't so visible when using miniters >= 0.1.

**Comment by lrq3000** [comment] 2015-11-10 20:15
Just for fun:
http://changaco.oy.lc/unicode-progress-bars/

**Comment by casperdcl** [comment] 2015-11-10 21:12
lol :) wanna swap to filling pie chart notation? it'll look more flashy than professional but won't have jitter effects (i think...)

**Comment by lrq3000** [comment] 2015-11-10 23:02
lol this could be a good idea :p seriously though, I think we should stay with what we have, this is not perfect in all situations, but it works good enough in most.

**Comment by lrq3000** [comment] 2015-11-10 23:03
But we of course may add other unicode progress bars, this is a simple matter of finding the ranges and add an if statement so that's not a big deal :)

**Comment by casperdcl** [comment] 2015-11-11 08:29
We could try and check if the environment is ipython/jupyter and handle things differently of so, but I'm against this as it draws attention away from the fact that those devs have messed with their fonts ... feel like there should be a new bug/issue opened with them :\

**Comment by kmike** [comment] 2015-11-11 11:05
Jupyter just uses `font-family:monospace`, I'm not sure this issue can/should be fixed by Jupyter.

**Comment by casperdcl** [comment] 2015-11-11 11:23
Hmm. Sounds like a system issue then...

**Comment by lrq3000** [comment] 2015-11-11 11:43
It's possible to change the font used by Jupyter. Maybe we can try to find one that is consistent on all platforms and force use it to draw tqdm's bar?

**Comment by lrq3000** [comment] 2015-11-11 11:44
Heck, if that's necessary, we may even supply our own font. I know that's just a workaround, but if this is really a system issue, then I'm pretty sure we will have more issues like this in the future...

**Comment by kmike** [comment] 2015-11-11 11:49
Another option is to use create a true HTML Jupyter widget with a progress bar, without relying on font symbols. I'm not sure how to implement it, but it must be possible (there are other progress bars with jupyter suport). It won't fix issue in other environments like android terminal emulator, but maybe that's fine.

**Comment by lrq3000** [comment] 2015-11-11 17:51
I'm not sure creating a HTML widget would fix the issue, except if we use javascript. Is this like what you had in mind?
http://www.jqueryscript.net/loading/Smooth-Progress-Bar-Loading-Effect-With-jQuery.html

**Comment by lrq3000** [comment] 2015-11-11 17:52
What I mean is that HTML alone cannot, to my knowledge, create a smooth progress bar, so we would anyway have to use an ascii bar. But it's possible with either javascript and/or css. But I'm not sure if Jupyter allows third party modules to tamper with the javascript as part of the security measures.

**Comment by kmike** [comment] 2015-11-11 18:03
@lrq3000 there is a built-in progress bar widget in IPython - see https://github.com/ipython/ipywidgets and its ipywidgets.widgets.FloatProgress. It must be possible to implement a similar widget if a default is not enough.

**Comment by lrq3000** [comment] 2015-11-11 20:42
Ah, I missed the FloatProgress widget. Indeed, I already used IPython widgets in the past, they are quite nice. It's possible to implement custom widgets, I've read a couple articles about that, but I'm not sure how we can do that from an imported module rather than from an IPython js plugin.

**Comment by lrq3000** [comment] 2015-11-11 20:43
So yeah, this might be a good lead, but we'd need an IPython hacking expert. Also, are the widgets definition stable now?

**Comment by carlodri** [comment] 2015-11-26 13:20
Well, the IPython widgets are showcased in the [Jupyter project page](http://jupyter.org/), so I think they are quite use-ready.

**Comment by lrq3000** [comment] 2015-11-26 22:17
@carlodri you're right, I didn't check their new webpage, my bad :) Yes if they showcase it, the API should be stable now.

**Comment by casperdcl** [comment] 2015-11-27 13:37
Hmm looks like there was a fork on the original repo https://github.com/z-m-k/tqdm/commit/637156169c2b861a3bcfd73bf9e1e6a29202930b

**Comment by lrq3000** [comment] 2015-11-28 02:23
@casperdcl nice finding! We could try to use this fork to kickstart this new feature here.

**Comment by lrq3000** [comment] 2016-05-15 00:10
Fixed in #90.

**Closed by lrq3000** 2016-05-15 00:10 UTC
Labels: bug

**Comment by kmike** [comment] 2016-05-15 08:53
Awesome, thanks! 
By the way, when will 4.6.0 appear in pypi?

**Comment by lrq3000** [comment] 2016-05-15 12:49
I will publish it now :)

2016-05-15 10:53 GMT+02:00 Mikhail Korobov <notifications@github.com>:
