### ISSUE TITLE
Unexpected space between nested progress bars, growing on each iteration with jupyterlab

### ISSUE THREAD

**Issue by clemej** [tqdm/tqdm#550] opened 2018-05-09 15:13 UTC
It's certainly possible I've missed something in the docs, but the following code does not quite work as expected when run in jupyterlab.  Every time the second (nested) progressbar finishes, it seems to move one tick (half a line? a full newline?) further away from the  top bar.  So after each iteration, the bar moves further and further away. 

The same code construct using non-notebook versions of tqdm works fine on the command line. Not sure if this is a firefox rendering issue, a jupyterlab issue, or a tqdm issue. 

code:
```
from tqdm import tnrange, tqdm_notebook
import time

for o in tnrange(20, desc='Outer', ):
    for phase in ['phase1', 'phase2']:
        with tqdm_notebook(total=10 if phase=='phase1' else 5,
                               desc='{}'.format(phase), leave=False) as pbar:
            if phase == 'phase1':
                for e in range(10):
                    time.sleep(1)
                    pbar.update(1)
            else:
                for e in range(5):
                    time.sleep(1)
                    pbar.update(1) 
```

python version: Python 3.6.5 (ubuntu 18.04)
tqdm version: 4.23.3 via pip
```
$ pip3 list | grep jupyter
jupyter (1.0.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
jupyterlab (0.32.1)
jupyterlab-launcher (0.10.5)
```
Firefox version: 59.0.2 (ubuntu package release)

- [X] I have visited the [source website], and in particular
  read the [known issues]
- [X] I have searched through the [issue tracker] for duplicates
- [X] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment] 2018-05-09 15:14
dupe of #433 I think

**Closed by casperdcl** 2018-05-09 15:14 UTC
