### ISSUE TITLE
Can't display a process bar in a fixed line, in Windows 7 cmd and powershell CLI.

### ISSUE THREAD

**Issue by purpleskyfall** [tqdm/tqdm#499] opened 2018-01-10 02:52 UTC
I'm using Python 3.5.4, Windows 7 SP1, and tqdm 4.19.5.

When I using tqdm, it can't display a process bar in a fixed line but always start a new line in my PC. But if set `ascii=True`, it works good very well. Did I find a bug?

![tqdm](https://user-images.githubusercontent.com/25096239/34753646-128f5eae-f5f4-11e7-9c5b-9d8da30cf8af.PNG)

**Comment by casperdcl** [comment] 2018-01-10 10:17
duplicate of #454

**Closed by casperdcl** 2018-01-10 10:17 UTC
