### ISSUE TITLE
.close method to raise a ValueError

### ISSUE THREAD

**Issue by andreamoro** [tqdm/tqdm#970] opened 2020-05-13 16:30 UTC
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [X] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [ ] I have visited the [source website], and in particular
  read the [known issues]
- [ ] I have searched through the [issue tracker] for duplicates
- [ ] I have mentioned version numbers, operating system and
  environment, where applicable:

```
4.46.0 3.8.2 (default, May  2 2020, 09:39:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] darwin
```

When using the tdqm in the following way, my understanding is I need to do call the .close method at the end. In doing so I get a valueError printed in the console (while debugging).

```
pbar = tqdm(total=len(mylist), desc=f'Processing ...', unit="ID")
  
for in in range(len(mylist):
    ... do something
    pbar.update(1)

pbar.close()
```

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1775, in stoptrace
    debugger.exiting()
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1461, in exiting
    sys.stdout.flush()
ValueError: I/O operation on closed file.

I appreciate the error message is mostly related to pyCharm in this case, but I cannot figure out the reason.

**Comment by casperdcl** [comment] 2020-05-14 09:32
Odd; seems like an issue with the debugger. If you look at the stack trace there's no mention of `tqdm`.

**Comment by casperdcl** [comment] 2020-05-16 14:00
ah this looks like a duplicate of #202

**Closed by casperdcl** 2020-05-16 14:00 UTC
Labels: invalid, need-feedback
