### ISSUE TITLE
Supress initial display when creating a tqdm notebook widget

### ISSUE THREAD

**Issue by elvinlemmens** [tqdm/tqdm#954] opened 2020-04-29 10:00 UTC
I was wondering if it would be possible to have an option to disable the initial display action when creating a tqdm notebook widget, so that one could place the widget where it would be needed instead of always displaying it.

**Comment by casperdcl** [comment] 2020-04-29 13:27
duplicate of #909

**Closed by casperdcl** 2020-04-29 13:27 UTC
Labels: duplicate, invalid, submodule-notebook

**Comment by elvinlemmens** [comment] 2020-04-29 14:15
I don't think it is in fact a duplicate of the issue you posted. I think it due to the `display(container)` in `tqdm.notebook.py`. If you make this optional, one could manually display the widget where one would need it by using the container parameter to add it to a parent widget.
