### ISSUE TITLE
Garbled output on ipython console in windows

### ISSUE THREAD

**Issue by mahadi** [tqdm/tqdm#105] opened 2016-01-11 15:46 UTC
Hi, i am getting the following output in windows when i import tqdm

```
Python 2.7.11 |Anaconda 2.0.1 (32-bit)| (default, Dec  7 2015, 14:13:17) [MSC v.
1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 2.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from tqdm import tqdm

☺☻In [☺☻2☺☻]: ☺☻
```
Any idea why this happens?
tqdm version is 3.4.0

**Comment by casperdcl** [comment] 2016-01-11 17:58
This doesn't make sense... you're getting weird output just by importing the class? Not even creating an instance?

**Comment by mahadi** [comment] 2016-01-11 18:35
Yes. Also when i hit TAB after the last character of the import statement i get an exception. (will post the details tomorrow) 

Am 11. Januar 2016 18:58:08 MEZ, schrieb Casper da Costa-Luis <notifications@github.com>:
>This doesn't make sense... you're getting weird output just by
>importing the class? Not even creating an instance?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tqdm/tqdm/issues/105#issuecomment-170634604

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mahadi** [comment] 2016-01-11 18:58
I just tried this at home. The same problem in ipython. But in ptpython and ptipython its working. Some time ago i had a problem with \ in ptpython which is solved now. Perhaps its related to the same thing but i didnt take a look into this yet. See https://github.com/jonathanslenders/ptpython/issues/28

**Comment by casperdcl** [comment] 2016-01-11 20:23
Seeing as this issue isn't reproducible in other environments or on my machine, I think it's a problem with `ipython` on windows... maybe open an issue on their repo?

**Comment by lrq3000** [comment] 2016-01-11 23:35
No I think the issue is ours. I guess it's because IPython has its own color management library, which conflicts with `colorama`. This would explain why this happens only on Windows.
And indeed, I have just now reproduced the bug. If we comment `colorama.init()`, the bug disappears.

The problem is that we need colorama to make nested tqdm work, and ipython doesn't support the `terminal up` character natively.
To fix this issue, we could maybe try an alternative library such as [asciimatics](https://github.com/peterbrittain/asciimatics), or just load the part of colorama that pertains to the up character, and disable all the rest.

**Comment by lrq3000** [comment] 2016-01-11 23:37
Note that when `colorama.init()` is enabled, even if it garbles ipython's colored strings, the nested tqdm works flawlessly.

**Comment by mahadi** [comment] 2016-01-12 08:38
This is the output of the TAB completion
```
Python 2.7.11 |Anaconda 2.0.1 (32-bit)| (default, Dec  7 2015, 14:13:17) [MSC v.
1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 2.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from tqdm import tqdm
Readline internal error
Traceback (most recent call last):
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\console\console.py",
line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\rlmain.py", line 571,
 in readline
    self._readline_from_keyboard()
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\rlmain.py", line 536,
 in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\rlmain.py", line 556,
 in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\modes\emacs.py", line
 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\modes\emacs.py", line
 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\modes\basemode.py", l
ine 267, in complete
    self._display_completions(completions)
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\modes\basemode.py", l
ine 238, in _display_completions
    w, h = self.console.size()
  File "D:\Programme\Anaconda\lib\site-packages\pyreadline\console\console.py",
line 570, in size
    status = self.GetConsoleScreenBufferInfo(self.hout, byref(info))
ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_CONSOLE_SC
REEN_BUFFER_INFO instance instead of pointer to CONSOLE_SCREEN_BUFFER_INFO

☺☻In [☺☻1☺☻]: ☺☻
```

**Comment by lrq3000** [comment] 2016-01-14 22:02
Seems like this was already reported and fixed by `colorama` in v0.3.4 (current version is v0.3.6):

https://github.com/tartley/colorama/issues/53

@mahadi Can you try the latest `colorama` and tell us if this fixes your issue?

**Comment by lrq3000** [comment] 2016-01-15 10:07
Since I can reproduce the issue on my setup, I can confirm updating colorama should fix this issue. I close this ticket, please reopen if needed.

**Closed by lrq3000** 2016-01-15 10:07 UTC
Labels: bug

**Comment by mahadi** [comment] 2016-01-17 12:31
I also can confirm that updating colorama (latest was 0.3.6) solve the issue. Thanks for the investigation!

**Comment by lrq3000** [comment] 2016-01-17 14:05
Thank's for the feedback and glad it solved the issue :)

2016-01-17 13:31 GMT+01:00 mahadi <notifications@github.com>:
