### ISSUE TITLE
fractional total keyword can cause AssertionError in version 4.40

### ISSUE THREAD

**Issue by aronnem** [tqdm/tqdm#859] opened 2019-12-05 16:49 UTC
In the newest version, a fractional total can produce an AssertionError, where in previous versions it worked as expected. The documentation suggests that `total` can be a floating point value, so the error appears to be a bug. Here is a minimal reproducible example:

```python
import sys, tqdm
print(tqdm.__version__, sys.version, sys.platform)
for i in tqdm.tqdm(iterable=range(10), total=9.6):
    pass
```

Here is the output I get in an older tqdm version:
```
4.32.2 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] linux
10it [00:00, 74367.09it/s] 
```

Here is the output in 4.40.0:

```
4.40.0 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] linux
  0%|                                                                                                                                                                  | 0/9.6 [00:00<?, ?it/s\
]Traceback (most recent call last):
  File "tqdm_test.py", line 3, in <module>
    for i in tqdm.tqdm(iterable=range(10), total=9.6):
  File "/home/aronnem/miniconda3/envs/tqdm_test/lib/python3.6/site-packages/tqdm/std.py", line 1150, in __iter__
    self.close()
  File "/home/aronnem/miniconda3/envs/tqdm_test/lib/python3.6/site-packages/tqdm/std.py", line 1261, in close
    self.display(pos=0)
  File "/home/aronnem/miniconda3/envs/tqdm_test/lib/python3.6/site-packages/tqdm/std.py", line 1428, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/home/aronnem/miniconda3/envs/tqdm_test/lib/python3.6/site-packages/tqdm/std.py", line 1058, in __repr__
    return self.format_meter(**self.format_dict)
  File "/home/aronnem/miniconda3/envs/tqdm_test/lib/python3.6/site-packages/tqdm/std.py", line 482, in format_meter
    charset=Bar.ASCII if ascii is True else ascii or Bar.UTF)
  File "/home/aronnem/miniconda3/envs/tqdm_test/lib/python3.6/site-packages/tqdm/std.py", line 146, in __init__
    assert 0 <= frac <= 1
AssertionError
```
  [source website]: https://github.com/tqdm/tqdm/
  [known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
  [issue tracker]: https://github.com/tqdm/tqdm/issues?q=
  [StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by casperdcl** [comment] 2019-12-05 16:52
True - floating point rounding could result in `total < n` which should maybe warn rather than error.

**Comment by casperdcl** [comment] 2019-12-06 09:58
Related/duplicate of #849

**Closed** 2019-12-06 11:29 UTC
Labels: bug-critical, duplicate
