### ISSUE TITLE
Loading bars from tqdm.notebook (v4.64.0) do not show up in VSCode when using Ipywidgets (v8.0+). Ipywidgets (v7.7.1) works fine.

### ISSUE THREAD

**Issue by rodrigo-barraza** [tqdm/tqdm#1360] opened 2022-08-29 23:25 UTC
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment] 2022-08-30 17:03
probably duplicate of #1310?

**Closed** 2022-09-02 09:05 UTC
Labels: duplicate 🗐, to-fix ⌛, p2-bug-warning ⚠, submodule-notebook 📓
