### ISSUE TITLE
__repr__ function

### ISSUE THREAD

**Issue by MPagel** [tqdm/tqdm#462] opened 2017-10-04 16:00 UTC
At least canonically, `__repr__` isn't supposed to take any parameters other than the object instance (`self`)

https://github.com/tqdm/tqdm/blob/a8e586fd1371df147d9ebb809f8259411ad38124/tqdm/_tqdm.py#L889

This is why I had introduced self.elapsed.

Additionally, `__repr__` is supposed to be unambiguous (by my understanding) - no two tqdm objects should produce the exact same output (but they should give object addresses in memory or some such thing).  `__str__` is supposed to be the user-friendly view version. In tqdm's case, `__str__` or `__format__` might be the best calls to make. We might be able to rename format_meter to `__format__` and `__repr__` to `__str__`?

**Comment by MPagel** [comment] 2017-10-04 16:12
From [python docs (2.7) ](https://docs.python.org/2/reference/datamodel.html#object.__repr__)

> If at all possible, [the output of `__repr__`] should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment).

Stack thread comments to [How do I use `__repr__` with multiple arguments?](https://stackoverflow.com/q/40600268/4228193)

- [...`__repr__()` doesn't take any arguments...](https://stackoverflow.com/questions/40600268/how-do-i-use-repr-with-multiple-arguments#comment68436086_40600268)

- [This question is like asking how to drive nails with a banana. That is not what bananas are for, and this is not what `__repr__` is for. ...](https://stackoverflow.com/questions/40600268/how-do-i-use-repr-with-multiple-arguments#comment68436221_40600268)

**Comment by casperdcl** [comment] 2017-10-05 00:18
I knew and agree with everything posted above, but still opted for this as it's neater and to the best of my knowledge isn't broken or likely to break. `__repr__()` has no required positional arguments and storing and updating a new variable everywhere in lieu of the single line of code where the `__repr__()` optional argument is used seems too complicated.

I would be open to renaming functions though as mentioned in my relevant commit message

**Comment by casperdcl** [comment] 2018-04-08 19:12
closing for now since there's been no updates Happy to reopen if there's evidence that this is broken. Basically we have written a `__repr__()` with an optional keyword argument in order to do both what `__repr__()` was intended to do, as well as provide a neat, efficient way of making a small override. This also avoids code duplication. At the most we could prefix the optional argument with an underscore or two...

**Closed by casperdcl** 2018-04-08 19:12 UTC
