### ISSUE TITLE
Google Colab (& Jupyter Lab) bug: nested bars duplicated at each iteration

### ISSUE THREAD

**Issue by artemisart** [tqdm/tqdm#625] opened 2018-10-09 09:56 UTC
The output of google colab is a bit strange and it duplicate nested bars for each iteration:
```python
from time import sleep
from tqdm import tqdm
for j in tqdm(range(3), desc='main',position=0):
    for i in tqdm(range(3), desc='inner', position=1):  # it's exactly the same output if I omit the position args
        sleep(0.1)
```
```
main:   0%|          | 0/3 [00:00<?, ?it/s]
inner:   0%|          | 0/3 [00:00<?, ?it/s]
inner:  33%|███▎      | 1/3 [00:00<00:00,  9.98it/s]
inner:  67%|██████▋   | 2/3 [00:00<00:00,  9.84it/s]
inner: 100%|██████████| 3/3 [00:00<00:00,  9.74it/s]
main:  33%|███▎      | 1/3 [00:00<00:00,  3.05it/s]
inner:   0%|          | 0/3 [00:00<?, ?it/s]
inner:  33%|███▎      | 1/3 [00:00<00:00,  9.98it/s]
inner:  67%|██████▋   | 2/3 [00:00<00:00,  9.86it/s]
inner: 100%|██████████| 3/3 [00:00<00:00,  9.69it/s]
main:  67%|██████▋   | 2/3 [00:00<00:00,  3.03it/s]
inner:   0%|          | 0/3 [00:00<?, ?it/s]
inner:  33%|███▎      | 1/3 [00:00<00:00,  9.98it/s]
inner:  67%|██████▋   | 2/3 [00:00<00:00,  9.85it/s]
inner: 100%|██████████| 3/3 [00:00<00:00,  9.77it/s]
main: 100%|██████████| 3/3 [00:00<00:00,  3.02it/s]
```
However forcing the position of the nested bars to 0 seem to solve the issue:
```python
from time import sleep
from tqdm import tqdm
for j in tqdm(range(3), desc='main'):
    for i in tqdm(range(3), desc='inner', position=0):
        sleep(0.1)
```
```
inner: 100%|██████████| 3/3 [00:00<00:00,  9.89it/s]
inner: 100%|██████████| 3/3 [00:00<00:00,  9.90it/s]
inner: 100%|██████████| 3/3 [00:00<00:00,  9.90it/s]
main: 100%|██████████| 3/3 [00:00<00:00,  3.25it/s]
```
Version
```python
> import tqdm, sys
> print(tqdm.__version__, sys.version, sys.platform)
4.26.0 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] linux
```
So is this the expected behaviour ? Could the position be automatically forced to 0 if the env is a notebook ?
For long iterations it can crash the browser tab (both Firefox and Chrome) because the bar is duplicated thousands of times and google colab output display must not be that optimized.

EDIT: in fact the issue is not only on google colab, I am able to reproduce the same outputs in jupyter lab & notebook.

**Comment by casperdcl** [comment] 2018-10-13 12:39
duplicate of #558

**Closed** 2018-10-13 12:39 UTC
Labels: duplicate

**Comment by artemisart** [comment] 2018-10-13 12:50
This is clearly not a duplicate as #558 is about tqdm_notebook with js widgets and the bug I encounter is about text (stdout) tqdm. And yes I searched for similar issues before posting this but I found nothing related to my problem.

**Comment by casperdcl** [comment] 2018-10-13 12:55
Ah I see this is more like #428

**Comment by casperdcl** [comment] 2018-10-13 12:57
See also nested https://github.com/tqdm/tqdm#faq-and-known-issues

**Comment by artemisart** [comment] 2018-10-13 13:12
Indeed, but #428 doesn't provide an output example so I cannot really compare.
So is the problem "expected" for text output in notebooks ? Could tqdm detects that the output is a cell in a notebook and force position=0 ?

**Comment by casperdcl** [comment] 2018-10-15 01:27
forcing `position=0` would overwrite bars on top of each other, though.
