### ISSUE TITLE
Wrong spanish translation

### ISSUE THREAD

**Issue by brando90** [tqdm/tqdm#1090] opened 2020-12-04 20:24 UTC
I love you so much" in Spanish (te quiero demasiado).

is a wrong translation in Spanish.

So much in the context of love means te quiero tanto.

Demasiado means TOO MUCH.

**Comment by casperdcl** [comment] 2020-12-04 22:37
duplicate of #577 :smile:

**Closed by casperdcl** 2020-12-04 22:37 UTC
Labels: duplicate 🗐, question/docs ‽
