### ISSUE TITLE
Pandas.Panel FutureWarning may become Error

### ISSUE THREAD

**Issue by StanczakDominik** [tqdm/tqdm#824] opened 2019-10-20 10:45 UTC
It looks like `pandas.Panel` is being deprecated:

```[ins]
In [1]: import pandas                                                                                                                                   

[ins] In [2]: pandas.__version__                                                                                                                              
Out[2]: '0.25.1'

[ins] In [3]: import tqdm                                                                                                                                     

[ins] In [4]: tqdm.__version__                                                                                                                                
Out[4]: '4.36.1'

[ins] In [5]: tqdm.tqdm.pandas()                                                                                                                              
/progs/miniconda3/lib/python3.7/site-packages/tqdm/std.py:648: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
```

I haven't been able to find any other issues on this, so I figured I'd give you wonderful folks a heads up.

Is it going to be difficult to replace `Panel`?

**Comment by casperdcl** [comment] 2019-10-20 11:07
duplicate of #780

really annoying since

1. pandas major version is still `0` so they get to constantly break their API
2. I don't use pandas but still feel forced to support it since I wrote this wrapper

[![](https://img.shields.io/badge/gift-donate-dc10ff.svg)](https://caspersci.uk.to/donate)

**Comment by casperdcl** [comment] 2019-10-20 11:09
please reopen if (when) pandas breaks again

**Comment by StanczakDominik** [comment] 2019-10-20 11:09
Ah, apologies, I was looking for the FutureWarning in there. Of course, this is clearly the same issue - my bad.

**Comment by casperdcl** [comment] 2019-10-20 11:14
yes but still going to need reopening at some point in the future. I'm not going to bother divining a decent future-proof wrapper for their messy API and incessant design shifts

**Comment by dgrahn** [comment] 2019-10-29 11:35
I hate to do this, but I think we need to reopen this issue. I'm seeing this behavior with `pandas==0.25.2` and `tqdm==4.36.1`. So this is not covered by #780.

**Comment by casperdcl** [comment] 2019-10-29 12:28
@dgrahn you should only be seeing a `FutureWarning` - which I'm going to just leave in there for now. I don't think I should be removing such a warning.

I'd prefer to only reopen this issue if (when) the Warning becomes an Error... Or perhaps prevent that from ever happening. hmmm. 59f457a8ceb64f6aaf02113c035516c2caa181d4

**Comment by dgrahn** [comment] 2019-10-29 12:52
@casperdcl My change removes the warning by removing the Panel functionality. This is inline with usage for `pandas>=0.25.0`. This would prevent the warning from ever becoming an error.

**Comment by casperdcl** [comment] 2019-10-29 19:23
@dgrahn as `pandas` is a soft dependency (`tqdm` has no hard deps) this isn't feasible as we can't pin version numbers anywhere.

**Comment by dgrahn** [comment] 2019-10-29 19:56
Hmm... Perhaps an option to "enable panel support".

- Pardon my brevity. I sent this from my phone.

**Comment by casperdcl** [comment] 2019-10-29 21:24
I don't use pandas at all, and strongly believe nobody else should, yet I wrote `tqdm`'s wrapper for it in response to community demand. I feel said community of `pandas` aficionados expect default "it just works" as opposed to robust black&whitelisting.

**Comment by dgrahn** [comment] 2019-10-29 21:37
How about a default on?

And why the pandas hate?

- Pardon my brevity. I sent this from my phone.

**Comment by casperdcl** [comment] 2019-10-30 07:17
After 59f457a it'll be default on (as it is now) but also silently not break when they remove the functionality.

I know atm `tqdm.pandas` users who don't use `Panel` still see this message but I see that as a good thing highlighting a changing API.

**Comment by casperdcl** [comment] 2019-10-30 07:18
If there's any pandas core dev who disagrees then I'd be happy to suppress the warning

**Comment by dgrahn** [comment] 2019-10-30 12:15
So... "I don't like Pandas because they change their API. I want people to see a warning because I don't like Pandas. And I won't include an option to suppress that warning."?

**Comment by casperdcl** [comment] 2019-10-30 13:46
xD definitely not.

> I don't like Pandas because they change their API

I don't like `pandas` for many reasons, none of which I am under any obligation to explain owing to the thankless unfunded open source nature of my voluntary contributions. My expression of dislike is intended to spur `pandas` experts to fight back (ideally using code rather than words).

> I want people to see a warning because I don't like Pandas

I think `pandas` devs would want people to see a warning since `tqdm.pandas` is really beta anyway. Nobody's actually checked the code.

> And I won't include an option to suppress that warning

True, unless convinced otherwise. I believe 1) this will disappear when the functionality is removed (warning will turn into an Import Error which is caught by 59f457a8) and 2) I think it's fine to warn about default-on leaving users/devs to wrap code with a simple `warnings.filterwarnings` if they are happy to suppress it. Worst case scenario is lots of people wind up reading this issue and get vaguely perplexed. Better case is they get amused. Best is they contribute!

> I'm also failing to see an issue with dropping support for a deprecated piece of functionality

This is perhaps true for most software. However, unfortunately, with massively used things things like python2 and in the words of Joshua Bloch, APIs are forever.

**Comment by dgrahn** [comment] 2019-10-30 16:51
I mean... I was trying to contribute. I offered several solutions and
implemented one of them.

Maybe you'd have better luck if you forked tqdm pandas into its own library?

**Comment by casperdcl** [comment] 2019-11-05 12:01
Yes, perhaps. The thing is `pandas` is used widely enough and people in general prefer ease of use and installation (https://www.dreamsongs.com/RiseOfWorseIsBetter.html etc...). In general though I hope with #815 many different "here be dragons" contributions can be merged in without me feeling responsible or guilty :)

**Comment by casperdcl** [comment] 2019-11-21 22:42
closed by #834

**Closed by casperdcl** 2019-11-21 22:42 UTC
Labels: bug-critical, enhancement, eol, invalid, submodule, to-merge

**Comment by th0ger** [comment] 2020-03-27 22:59
I ended up reading this issue and got vaguely perplexed. Also got slightly amused. Unfortunately not contributing.

**Comment by casperdcl** [comment] 2021-02-18 03:51
FYI https://github.com/tqdm/tqdm/issues/1094#issuecomment-781018248:

> In any case `pandas>1.2.0` doesn't cause this error anyway (https://github.com/pandas-dev/pandas/pull/37983). Now that it's fixed, I'm ok with adding an extra suppression just for those still using older versions.

Warning will disappear using either `tqdm>=4.57.0` (#1127) or `pandas>=1.2.0`.
