### ISSUE TITLE
Automatically choose between tqdm and  tqdm_notebook

### ISSUE THREAD

**Issue by nthiery** [tqdm/tqdm#508] opened 2018-02-02 10:09 UTC
Use case: writing a module that can be used from either the command line or the notebook

Desired feature: have some wrapper on top of tqdm that detects whether the code is running in a notebook or not, and automatically chooses between tqdm or tqdm_notebook; same for trange and tnrange.

(btw: kudos for tqdm; it's super useful for tracking lengthy computations!)

**Comment by casperdcl** [comment] 2018-02-03 02:37
duplicate of #443

**Closed** 2018-02-03 02:38 UTC
Labels: duplicate

**Comment by nthiery** [comment] 2018-02-03 22:28
> duplicate of [1]#443

Thanks for making the connection; #443 had slipped through my keyword
search.

**Comment by casperdcl** [comment] 2018-02-04 09:00
no problem, feel free to volunteer an opinion there!
