### ISSUE TITLE
Jupyter Not works well when "break" in nested loop 

### ISSUE THREAD

**Issue by DYFeng** [tqdm/tqdm#553] opened 2018-05-17 15:21 UTC
```
from tqdm import tqdm_notebook

for i in tqdm_notebook(10, desc='1st loop'):
    for j in tqdm_notebook(5, desc='2nd loop', leave=False):
        sleep(0.01)
        break
```

**Comment by casperdcl** [comment] 2018-05-18 15:49
do you mean `tnrange` instead of `tqdm_notebook`?

**Comment by vcartillier3** [comment] 2018-05-23 16:32
Hi @DYFeng,
Not sure if this is what you meant but I had a similar issue while breaking a for loop within tqdm:
```python
for t in tqdm.trange(10):
      if t==5: break
```
yields to 
> Exception KeyError: KeyError(<weakref at 0x7f20e0958c58; to 'tqdm' at 0x7f20e094e190>,) in <bound method tqdm.__del__ of   ...

Here is a workaround:
```python
with tqdm.tqdm(total=10) as pbar:
     for t in range(10):
             if t==5:
                     pbar.close()
                     break
             pbar.update(1)
```
Hope this helps.
ubuntu 16.04
python 2.7
tqdm 4.23.4

**Comment by casperdcl** [comment] 2018-05-25 13:48
related: 548

**Comment by chengs** [comment] 2018-08-22 05:37
@casperdcl this is only in python2.x right?

**Comment by casperdcl** [comment] 2018-10-13 12:42
closing as duplicate of #548

**Closed** 2018-10-13 12:42 UTC
Labels: duplicate
