### ISSUE TITLE
set_description causes ghosting with long text

### ISSUE THREAD

**Issue by andrewspode** [tqdm/tqdm#690] opened 2019-03-04 10:52 UTC
I'm using set_description() with a filename, so I can easily show which file is currently being processed.

If a long filename comes along, I think it's becoming multiline, and then when the next file (that isn't long) comes up, it leaves a ghost trail on the screen, very similar to when you use print() instead of tqdm.write().

I have simply truncated my filenames to a fixed size, but in an ideal world it would be nice to have the option of truncating this automatically as you will know exactly how many characters there are left available on screen once everything else is rendered. I'm simply guessing.

Or, is this a rendering issue that can be fixed and leave the multiline implementation as is?

**Comment by casperdcl** [comment] 2019-03-04 19:40
duplicate of #582

**Comment by andrewspode** [comment] 2019-03-05 09:59
I'm not entirely sure I agree it's a duplicate - but that's up to you.

However, the ghosting is definitely undesirable. If it temporarily becomes multiline - I can cope with that, in fact, I would prefer that - but I just don't expect to see a ghost left behind when it switches back. So either that needs looking at, or we need the option of automatic cropping of the text to the available space to keep it on one line. 

Off the top of my head, you could do the string formatting for the bar (minus description) to get its length, then compare to the terminal width, and format for a second time to add the description in. Obviously a little slower, but if it was an optional parameter, I would pick it. 

Alternatively, if there was a way of requesting the number of characters in the progress bar, I could set the description to (""), request the number of characters, and then set the description length appropriately.

**Closed** 2019-12-20 17:43 UTC
Labels: duplicate, question
