### ISSUE TITLE
Unable to run tqdm with pandas

### ISSUE THREAD

**Issue by saadabbasi** [tqdm/tqdm#1206] opened 2021-07-18 19:48 UTC
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:

Python 3.7.10
Ubuntu 18.04.4 LTS
TQDM 4.61.1
Pandas 1.30

I am unable to run the demo provided in the [documentation](https://pypi.org/project/tqdm/#pandas-integration)

  ```import pandas as pd
import numpy as np
from tqdm import tqdm

df = pd.DataFrame(np.random.randint(0, 100, (100000, 6)))

# Register `pandas.progress_apply` and `pandas.Series.map_apply` with `tqdm`
# (can use `tqdm.gui.tqdm`, `tqdm.notebook.tqdm`, optional kwargs, etc.)
tqdm.pandas(desc="my bar!")

# Now you can use `progress_apply` instead of `apply`
# and `progress_map` instead of `map`
df.progress_apply(lambda x: x**2)
# can also groupby:
# df.groupby(0).progress_apply(lambda x: x**2)
  ```

This returns `AttributeError: 'DataFrame' object has no attribute '_is_builtin_func'`

Any thoughts on fixing this?

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=

**Comment by casperdcl** [comment] 2021-07-18 21:52
Duplicate of #1199

**Closed** 2021-07-18 21:52 UTC
Labels: duplicate 🗐, invalid ⛔, submodule ⊂
