### ISSUE TITLE
tqdm prints new lines when it updates (after a KeyboardInterrupt)

### ISSUE THREAD

**Issue by ziofil** [tqdm/tqdm#626] opened 2018-10-12 16:03 UTC
On jupyter-lab 0.34.3, I have the following issue: after a `KeyboardInterrupt`, the next time I run a cell where there's a tqdm loop, the progressbar prints new lines instead of replacing the existing line. The only "solution" that I have is to kill the kernel (not ideal!)

These are the details of my system:
4.26.0 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] darwin

<img width="609" alt="capture d ecran 2018-10-12 a 18 04 12" src="https://user-images.githubusercontent.com/8944955/46880614-76734380-ce49-11e8-936f-2e635963ca0f.png">

**Comment by casperdcl** [comment] 2018-10-13 12:43
duplicate of #548

**Closed** 2018-10-13 12:43 UTC
Labels: duplicate
