### ISSUE TITLE
tqdm_notebook not always appearing

### ISSUE THREAD

**Issue by jmerkow** [tqdm/tqdm#170] opened 2016-05-27 14:51 UTC
I am using jupyter notebook 4.1.0, tqdm 4.7.0-22a00f0, ipywidgets 4.1.1.
The tqdm_notebook does not always appear, or rather I should say it sometimes appears.
I understand this is an experimental feature.

``` python
from tqdm import tqdm, tqdm_notebook
import time
for i in tqdm_notebook(range(1)):
    time.sleep(.1)
```

Only blank space appears and I get the following errors in the js debugger:

```
Could not open comm (2)
" -- "
Error: Class ipython.widget not found in registry
(anonymous function) — main.min.js:18267
initializePromise
Promise
load_class — main.min.js:18252
comm_open — main.min.js:38185
i — main.min.js:300
_handle_iopub_message — main.min.js:39582
_finish_ws_message — main.min.js:39399
(anonymous function) — main.min.js:39387
promiseReactionJob
(anonymous function) — main.min.js:18303
promiseReactionJob


Couldn't process kernel message
Error
column: 30
error_stack: [Error: Class ipython.widget not found in registry , Error: Could not open comm] (2)
line: 12761
message: "Could not open comm"
sourceURL: "http://localhost:8889/static/notebook/js/main.min.js?v=5583f76ed439d168d24e1b201697c328"
stack: "WrappedError@http://localhost:8889/static/notebook/js/main.min.js?v=5583f76ed439d168d24e1b201697c328:12761:3…"
```

**Comment by casperdcl** [comment] 2016-05-27 15:00
tqdm 4.7.0-22a00f0? I can't see any commit hash `22a00f0` in tqdm's history... did you modify it?

**Comment by jmerkow** [comment] 2016-05-27 18:30
No.  I just upgraded with pip install --upgrade tqdm

**Comment by casperdcl** [comment] 2016-05-27 19:50
oh ok. I'm guessing you did a `tqdm --version` in a repo with that commit id and the logic picked it up. anyway @lrq3000 should be better placed to answer your question

**Comment by lrq3000** [comment] 2016-05-28 20:22
The key error seems to be this line:

```
error_stack: [Error: Class ipython.widget not found in registry , Error: Could not open comm] (2)
```

[From this issue on ipywidgets repo](https://github.com/ipython/ipywidgets/issues/233#issuecomment-158017729), it seems this issue may be caused by a mismatch between conda installed jupyter, and pip installed ipywidgets. Both should be installed via the same method.

Could you please try to uninstall both packages and reinstall them both with one package manager?

**Comment by jmerkow** [comment] 2016-05-29 00:42
Both were installed with pip in a virtualenv. I do not use conda

**Comment by lrq3000** [comment] 2016-05-29 08:58
Can you try to execute this code in an IPython notebook and report to us the result?

```
from ipywidgets import IntSlider
IntSlider()
```

**Comment by lrq3000** [comment] 2016-05-29 09:14
Also, did you install `widgetsnbextension` (previously known as `jupyter-js-widgets-nbextension`, and previously unnecessary before ipywidgets 4.1)?

You can also try to install ipywidgets 4.0 instead of ipywidgets 4.1, [this may fix your issue according to this PR](https://github.com/jupyter/notebook/pull/1022/commits/ee7dd22ebeefe4e279f31268313ae7ede8058a7e#r51210878).

**Comment by jmerkow** [comment] 2016-05-29 16:38
Still is not working.  
The strange part is that it works in some notebooks and not others. It also may work for a while in a particular notebook, then just stop working.  If I copy-paste each cell individually into a new notebook, it may work in the new one...

**Comment by lrq3000** [comment] 2016-05-29 20:27
When tqdm is failing, please try to run:

```
from ipywidgets import IntSlider
IntSlider()
```

Just to see if this reproduces the problem. My guess is that due to ipywidgets very recent refactoring, the widgets are now very unstable.

You could try to uninstall Jupyter and ipywidgets, and install Jupyter 4.0 and ipywidgets 4.0. This setup is known to work quite reliably, it's just before the refactoring that started in ipywidgets 4.1.

**Comment by wernight** [comment] 2016-06-01 22:39
Interestingly I've almost the opposite: It always shows but sometimes there is an additional light blue bar remaining before the normal one. One with text like `0/|/1st loop: 0% 0/10 [00:00<?, ?it/s]`

**Comment by lrq3000** [comment] 2016-06-01 23:06
@wernight The light blue bar is normal and is part of the `tqdm_notebook` initialization. But the light blue bar should always disappear and be replaced by the correct one (except if there is no `__len__` for the iterable you provide, in this case the light blue bar stays).
I can maybe find a way to workaround that but that's tricky (it happens because `tqdm_notebook` inherits from `tqdm`, the light blue bar is used as a con bar during `tqdm` initialization, and then gets replaced when `tqdm_notebook` continue with its own initialization code)

**Comment by wernight** [comment] 2016-06-02 08:07
![image](https://cloud.githubusercontent.com/assets/145667/15738046/aae1e40c-28a9-11e6-831f-06f60e67245c.png)

It doesn't disappear 80% of the time (about).

**Comment by lrq3000** [comment] 2016-06-02 09:32
@wernight Thank you for reporting this issue. Can you please try the [patch here](https://github.com/tqdm/tqdm/tree/notebook-fix) to see if it fixes your issue?

**Comment by jmerkow** [comment] 2016-06-11 15:31
IntSlider() also does not show up.  I'll try downgrading.  Anything else I can try?

**Comment by lrq3000** [comment] 2016-06-11 17:40
Thank you for testing jmerkow. There's no other test that I am aware of, but you make try to ask on ipywidgets github. But anyway, if IntSlider() doesn't show up, then there's something wrong with ipywidgets, so the best bet is to downgrade to 4.0.

**Comment by wernight** [comment] 2016-06-16 18:58
@lrq3000 Sorry for the delay. I tried the new version and it works perfectly. I didn't expect to find one of the iP4D players here! 🎉

**Comment by jmerkow** [comment] 2016-06-17 04:29
I downgraded seems to work consistently.

**Comment by lrq3000** [comment] 2016-07-03 22:01
@wernight Great, I didn't expect to find the iP4D author here neither ;p Opensource is great for that!!

Thank you both @wernight and @jmerkow for reporting, I hope the issue will be sorted out soon!

**Comment by casperdcl** [comment] 2016-12-06 16:59
closing this for now as it seems this is an issue related to another package, not `tqdm`

**Closed by casperdcl** 2016-12-06 16:59 UTC
Labels: bug-error, bug-warn, invalid
