### ISSUE TITLE
Progressbar stick to the bottom of terminal

### ISSUE THREAD

**Issue by BoPeng** [tqdm/tqdm#816] opened 2019-09-17 23:55 UTC
I am running `apt dist-upgrade` on one of my ubuntu VMs and notice that the screen has a scroll log and a scroll bar at the bottom showing the overall progress. This looks very useful because right now I can have either a progress bar or log text, not both. Is this something tqdm can do? If not, what it takes to achieve this effect? 

![image](https://user-images.githubusercontent.com/9889312/65087689-5367e280-d97c-11e9-876e-139938e1cd60.png)

**Comment by casperdcl** [comment] 2019-09-17 23:57
duplicate of #785

**Closed by casperdcl** 2019-09-17 23:57 UTC
Labels: duplicate
