### ISSUE TITLE
print/get final nested progbar stats iterations/sec

### ISSUE THREAD

**Issue by ahundt** [tqdm/tqdm#660] opened 2019-01-19 19:57 UTC
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```

I'd like to get final stats from a nested progbar such as:
- it/s
- total time 
- total steps

It seems `tqdm(leave=True)` by default, but only the outer progbar rather than nested progbars leave anything behind. Another alternative would be to have a way to get the final stats out of the tqdm progbar after it is done iterating, and I could write them out myself.

Is this doable?

Slightly related issue:
https://github.com/tqdm/tqdm/issues/230

Side note: I've been using tqdm all the time for years now. It is pretty amazing, thanks!

**Comment by casperdcl** [comment] 2019-01-19 21:56
think this is a duplicate of #562.

For now you can:


```
for x in tqdm(...):
    with tqdm(...) as nested:
        for y in nested:
            ...
        stats = str(nested)
        # now parse/extract info from `stats`
```

**Comment by ahundt** [comment] 2019-01-23 21:43
thanks, that seems like it will do the trick for now

**Closed** 2019-01-23 22:18 UTC
Labels: duplicate, enhancement, question
