### ISSUE TITLE
Installing 4.8.2 results in SyntaxError

### ISSUE THREAD

**Issue by weatherfrog** [tqdm/tqdm#219] opened 2016-08-01 10:24 UTC
Installing the latest version 4.8.2 results in an error (4.8.1 works fine):

```
$ pip install tqdm==4.8.2
Downloading/unpacking tqdm==4.8.2
  Downloading tqdm-4.8.2-py2.py3-none-any.whl (42kB): 42kB downloaded
Installing collected packages: tqdm
*** Error compiling '/home/rg/workspace/nwpDownloaders/venv/build/tqdm/tqdm/PairList.py'...
  File "/home/rg/workspace/nwpDownloaders/venv/build/tqdm/tqdm/PairList.py", line 21
    print z
          ^
SyntaxError: Missing parentheses in call to 'print'
```

Tested with Python 3.4 on Linux.
Not sure where this is comming from.

**Comment by casperdcl** [comment] 2016-08-01 10:35
oops, sorry, that file should not have been on pypi.

**Comment by lrq3000** [comment] 2016-08-06 12:29
@casperdcl Is it fixed? Maybe we can close this issue?

**Comment by casperdcl** [comment] 2016-08-06 12:40
yup, put 4.8.3 on instead. the 4.8.2 pypi package picked up a test file of
mine accidentally..

**Comment by lrq3000** [comment] 2016-08-06 13:21
Yeah I guessed about it, I also did the same mistake in the past XD Great so we can close this issue! (just 24 to go lol...).

**Closed by lrq3000** 2016-08-06 13:21 UTC
Labels: bug

**Comment by CrazyPython** [comment] 2016-08-06 22:19
@casperdcl how'd it go unnoticed by the tests?

**Comment by lrq3000** [comment] 2016-08-07 11:28
@CrazyPython IIRC, it's because setuptool or distutils includes all .py files in the package. That's by design, because it seemed to be the most sensible choice for most builds. Maybe we can override this behavior, but this would imply that we will need to edit the setup.py file everytime we add a new .py file, so this will probably lead to mistakes. Anyway, this is why it's not detected by the tests, because we don't test the build process (and anyway even if we did, we would have to check that only the files we want are present in the builds, which is practically the same as explicitly specifying in setup.py the list of .py files to include in builds).
