### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'sp'

### ISSUE THREAD

**Issue by BastianZim** [tqdm/tqdm#1103] opened 2020-12-25 14:41 UTC
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
---
Hi, I'm getting the following error: `AttributeError: 'tqdm' object has no attribute 'sp'`

I realise that this has been reported before but wanted to open an extra issue since the other issues are about `tqdm_notebook`. (See #944 for example)

The full error:

```python
Exception ignored in: <function tqdm.__del__ at 0x7f9fe1a750d0>
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/env-name/lib/python3.8/site-packages/tqdm/std.py", line 1124, in __del__
    self.close()
  File "/Users/username/opt/anaconda3/envs/env-name/lib/python3.8/site-packages/tqdm/notebook.py", line 271, in close
    self.sp(bar_style='danger')
AttributeError: 'tqdm' object has no attribute 'sp'
```

I'm not using tqdm directly but as a part of https://github.com/flairNLP/flair

The code is:

```python
from flair.data import Sentence
from flair.models import TextClassifier


def _get_sentiment(text):
    classifier = TextClassifier.load("sentiment")
    sentence = Sentence(text)
    classifier.predict(sentence)
    result = sentence.to_dict()
    sentiment = result.get("labels")
    return sentiment
```

My environment is:

```python
4.54.1 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] darwin
```

I'm using [Spyder](https://github.com/spyder-ide/spyder) and no idea why, but the error doesn't happen all the time.

If there is anything else you need to know, just let me know!

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
[StackOverflow#tqdm]: https://stackoverflow.com/questions/tagged/tqdm

**Comment by BastianZim** [comment] 2020-12-25 14:42
Just to add: Since I'm not using tqdm directly, so I cannot skip it when executing my code. Is there a wrapper or something similar that I can use to skip it? The code will be executed headless so there is no need for a status bar.

**Comment by casperdcl** [comment] 2020-12-25 14:48
Can you try with the latest version just released (`tqdm>=4.55.0`)

**Comment by BastianZim** [comment] 2020-12-25 14:55
Thanks for the quick feedback!

```python
print(tqdm.__version__, sys.version, sys.platform)
4.55.0 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] darwin
```

gives now the following error:

```python
Exception ignored in: <function tqdm.__del__ at 0x7f8af881bee0>
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/env-name/lib/python3.8/site-packages/tqdm/std.py", line 1126, in __del__
    self.close()
  File "/Users/username/opt/anaconda3/envs/env-name/lib/python3.8/site-packages/tqdm/notebook.py", line 288, in close
    self.disp(bar_style='danger')
AttributeError: 'tqdm' object has no attribute 'disp'
```

**Comment by casperdcl** [comment] 2020-12-26 16:40
I think this is a duplicate of #944... it seems to be a problem when a python process exits and doesn't clean up properly. Notice it says "Exception ignored" so isn't actually causing a crash...

**Closed by casperdcl** 2020-12-26 16:40 UTC
Labels: duplicate 🗐, p2-bug-warning ⚠, submodule-notebook 📓

**Comment by BastianZim** [comment] 2020-12-26 16:42
Ok, makes sense!
