### ISSUE TITLE
Random deadlocks under PyPy

### ISSUE THREAD

**Issue by Mehechiger** [tqdm/tqdm#718] opened 2019-04-21 13:52 UTC
Hi there,
I have encountered a strange issue probably caused by tqdm: my program randomly freezes (completely, stops) under PyPy and I have to finally Ctrl+C it. And PyPy then returns the diagnostics which seem that it freezes in a tqdm loop. No pbs with cpython, it's just with PyPy. Thanks in advance!

 ```4.31.1 3.6.1 (dab365a465140aa79a5f3ba4db784c4af4d5c195, Feb 18 2019, 10:53:27)
[PyPy 7.0.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] darwin
```

```126     @clock
127     def simsCal(self):
128     │   print("Calculating words similarities...")
129     │   sims = {}
130     │   for wVecsCATk, wVecsCATv in self.wVecs.items():
131     │   │   simsCAT, CaledPairs = {}, {}
132     │   │   for wVec1k in tqdm(wVecsCATv.keys()):
133     │   │   │   simsWord = {}
134     │   │   │   wVec1 = wVecsCATv[wVec1k]
135     │   │   │   for wVec2k in wVecsCATv.keys():
136     │   │   │   │   if wVec2k == wVec1k:
```
 
```100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:59<00:00,  7.45s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 18.14it/s]
Calculating words similarities...
 75%|██████████████████████████████████████████████████████████████████████████████████████▍                             | 2117/2839 [00:20<00:05, 135.65it/s]^CTraceback (most recent call last):
  File "AzDist_0.8.6.py", line 173, in <module>
    for key, value in dist.simsCal().items():
  File "AzDist_0.8.6.py", line 16, in clocked
    result = func(*args, **kwargs)
  File "AzDist_0.8.6.py", line 132, in simsCal
    for wVec1k in tqdm(wVecsCATv.keys()):
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/tqdm/_tqdm.py", line 1041, in __iter__
    with self._lock:
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/tqdm/_tqdm.py", line 98, in __enter__
    self.acquire()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/tqdm/_tqdm.py", line 91, in acquire
    lock.acquire()
KeyboardInterrupt
^CTraceback (most recent call last):
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/tqdm/_monitor.py", line 53, in exit
    self.join()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
debug: OperationError:
debug:  operror-type: KeyboardInterrupt
debug:  operror-value:
```

**Comment by koriakin** [comment] 2019-05-01 11:19
I have traced it down to a pypy bug, which has just been fixed on pypy master: https://bitbucket.org/pypy/pypy/issues/2953/deadlock, would be nice to get a confirmation with nightly pypy.

**Comment by koriakin** [comment] 2019-05-01 11:19
Also, duplicate of #627

**Comment by casperdcl** [comment] 2019-05-09 16:25
duplicate of #528 yes

**Closed** 2019-05-09 16:25 UTC
Labels: bug-critical, synchronisation
