### ISSUE TITLE
Doesn't work in Sublime + SublimeREPL?

### ISSUE THREAD

**Issue by Gabriel-p** [tqdm/tqdm#99] opened 2016-01-04 16:38 UTC
I'm using Sublime + [SublimeREPL](https://github.com/wuub/SublimeREPL) to run some Python scripts.

This package does not seem to work, the progress is not updated "in place" but repeated over and over on the same line.

This is what I see:

    CR  0%|          | 0/25000 [00:00<?, ?it/s]CR  0%|          | 2/25000 [00:00<22:34, 8.46it/s]CR  0%|          | 4/25000 [00:00<22:36, 18.42it/s]CR  0%|          | 6/25000 [00:00<22:37, 18.41it/s]CR  0%|          | 8/25000 [00:00<22:38, 18.39it/s]

**Comment by nabijaczleweli** [comment] 2016-01-04 16:51
What you're seeing is probably ANSI escape codes. Try downloading the `ANSIescape` plugin and using the `ANSI` syntax highlighting. This is *not* `tqdm`'s fault/problem, it's yours.

**Comment by Gabriel-p** [comment] 2016-01-04 17:42
I installed that package in Sublime and now instead of being attached to the end of a single line, new outputs of tqdm are printed on a new line.

I've checked and I see the same behavior using the terminal. I'm using the default terminal from elementary OS 0.3.2 Freya 64-bit (based on Ubuntu 14.04).

**Comment by casperdcl** [comment] 2016-01-04 17:44
The `CR` at the end of lines in your output stands for "carriage return," which most terminals/consoles/prompts interpret as "move the cursor to the start of the current line."

The plugin mentioned above should get sublime slightly more compliant. Let us know if it doesn't work!

**Comment by Gabriel-p** [comment] 2016-01-04 17:46
Hi @casperdcl! As I said above, after installing the plugin the output I get look like this:

````

  0%|          | 0/25000 [00:00<?, ?it/s]0
1

  0%|          | 2/25000 [00:00<23:27, 17.76it/s]2
3

  0%|          | 4/25000 [00:00<23:24, 17.79it/s]4
5

  0%|          | 6/25000 [00:00<23:22, 17.82it/s]6
7

  0%|          | 8/25000 [00:00<23:21, 17.83it/s]8
9

  0%|          | 10/25000 [00:00<23:21, 17.83it/s]10
11

  0%|          | 12/25000 [00:00<23:17, 17.89it/s]12
````

I see the same output using the system's terminal.

**Comment by casperdcl** [comment] 2016-01-04 17:48
Hmm that seems to imply the `CR` is being interpreted as `LF` (line feed).

**Comment by casperdcl** [comment] 2016-01-04 17:54
https://github.com/wuub/SublimeREPL/issues/322

Looks like it's an old issue with sublime, maybe the workaround in the issue on their repo helps?

**Comment by Gabriel-p** [comment] 2016-01-04 19:35
Tried the fix mentioned in https://github.com/wuub/SublimeREPL/issues/322#issuecomment-75386600 but it did not work.

**Comment by lrq3000** [comment] 2016-01-09 01:22
I can confirm the issue, and that the fix proposed by SublimeREPL devs does not work.

Canonic code to reproduce the bug:
```
import sys
for i in xrange(10):
	sys.stdout.write("\rHello%i" % i)
	sys.stdout.flush()
```

In other words, any display using carriage return won't work with SublimeREPL. This is a big issue, but unfortunately not fixable by us. I thus close the issue.

**Closed by lrq3000** 2016-01-09 01:22 UTC
Labels: wontfix
