### ISSUE TITLE
jupyterlab start new lines while setting the param leave=False

### ISSUE THREAD

**Issue by dear-catchlove** [tqdm/tqdm#848] opened 2019-11-21 12:35 UTC
I use tqdm.notebook.tqdm in two loops. When I set the param leave=True in the seconde loop, it always start a new line as it run over the loop.

**Comment by dear-catchlove** [comment] 2019-11-21 12:40
Here I paste my code:

`from tqdm import notebook
import time

for i in notebook.tqdm(range(10)):
    for j in notebook.tqdm(range(10), leave=False, desc='Second Loop',position=-1,):
        time.sleep(0.05)`

**Comment by e-dorigatti** [comment] 2020-05-20 08:30
This is an issue with ipywidgets. I opened [an issue there](https://github.com/jupyter-widgets/ipywidgets/issues/2880)

**Comment by casperdcl** [comment] 2020-05-21 09:18
duplicate of #433

**Closed by casperdcl** 2020-05-21 09:18 UTC
