### ISSUE TITLE
add codecov.io support

### ISSUE THREAD

**Issue by kmike** [tqdm/tqdm#37] opened 2015-10-12 12:06 UTC
What about adding codecov.io support? 

Advantages of codecov:

1) it can mark build as failed if a patch coverage is less than X% (a good value is 100, this is configurable);
2) it uses branch coverage by default;
3) it can show coverage report for a patch (see example at https://github.com/scrapy/scrapy/pull/1528).

They can run with coveralls in parallel for some time, then we can disable one of them. In Scrapy (1) works wonderful: contributors are writing more and better tests, and merging an undercovered PR is now a deliberate decision.

**Comment by lrq3000** [comment] 2015-10-12 12:38
Ahhh good old Scrapy! Nice to see the project is still maintained :)

I didn't know about codecov.io, but it looks nice, I particularly like the fact that it gives the coverage rate and diff for each PR.

+1 for codecov.io support, but let's just not become coverage fanatics (I think the coverage failure threshold should be something around 70%~80%, so that experimental branches developping huge new features such as GUI won't systematically be marked as failures).

**Comment by casperdcl** [comment] 2015-10-12 16:39
:+1: to having something slightly lower than 100 to allow for big beta releases, but really these should have at least some major tests so 70% I think is too low.

**Comment by hadim** [comment] 2015-10-12 18:01
+1

**Comment by lrq3000** [comment] 2015-10-12 18:41
70% is clearly too low for the stable releases, so ideally, it would be great to have two different thresholds: one at something like 85%~90% for the master branch, and 70% by default for any other branch, so that we could develop experimental features without worrying too much about failing builds. But I don't know if that's possible with codecov.

**Comment by kmike** [comment] 2015-10-12 18:47
IMHO all numbers are arbitrary and it is human who should decide if test coverage is enough for a specific case; 100% is also an arbitrary number (it doesn't mean that all cases are covered), but it is at least a bit less arbitrary. Red cross makes wonders :) You can still have Travis build green, but Codecov build red.

**Comment by lrq3000** [comment] 2015-10-12 19:13
Ok then if there's no conflict of build failure between Codecov and Travis then we can set a high bar. I say we set at 90% for now, and we will see later if this needs to be reajusted.

Who want to take care of adding tqdm to codeconv? I tried to do it with my accound but it doesn't work (however I already granted the permission on github organization settings).

**Comment by lrq3000** [comment] 2015-10-12 19:20
Ok I'm doing it, tqdm org is now showing at the top bar of codecov. Must be some delay between granting permission and the update being propagated back to their website.

**Comment by kmike** [comment] 2015-10-12 19:29
Works now, thanks! I've enabled 80% incremental coverage build status and PR comments.

**Comment by lrq3000** [comment] 2015-10-12 19:34
Yes all done now, we will see with the next PR if it works correctly with PRs.

OK I also left the 80% threshold (the default value), because it's not a global coverage threshold, but an incremental coverage threshold (ie, the coverage of the newly introduced lines of codes, not the rest!), so 80% is already a pretty high bar in my opinion.

Thank's for the proposition @kmike :) I am also eager to try out the [Suggestions](https://codecov.io/github/tqdm/tqdm/features/suggestions?ref=master) feature :D

**Closed** 2015-10-12 19:35 UTC

**Comment by lrq3000** [comment] 2015-10-13 13:42
I just confirmed it works in PR, so everything's good :)
