### ISSUE TITLE
Multiline in Linux shell

### ISSUE THREAD

**Issue by GarrettGaoge** [tqdm/tqdm#985] opened 2020-06-03 17:15 UTC
I run my script on linux and use "screen -S" to create a virtual screen.
But the bar is moving up each line.
While there's no problem when I directly run the script without the virtual screen.
![image](https://user-images.githubusercontent.com/44859191/83667318-c4315680-a600-11ea-800b-b90964d3e395.png)

**Comment by casperdcl** [comment] 2020-06-03 19:10
duplicate of #877 - it's an issue with `screen`; perhaps you could try using `tmux` instead?

**Closed by casperdcl** 2020-06-03 19:10 UTC
Labels: bug-warning, duplicate, invalid

**Comment by GarrettGaoge** [comment] 2020-06-04 00:42
> duplicate of #877 - it's an issue with `screen`; perhaps you could try using `tmux` instead?

Thx very much! It's very helpful. I will try it.
