### ISSUE TITLE
Issue with hex colour in VS Code terminal

### ISSUE THREAD

**Issue by EmidioStani** [tqdm/tqdm#1298] opened 2022-02-10 19:01 UTC
- [x] I have marked all applicable categories:
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.62.3 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)] win32 

Hello I am running my python script in the terminal of Visual Studio Code (in dark mode), when I use the predefined colours  like (RED, YELLOW, etc.) I can see the progress bar in that colour (see yellow in screenshot) but when I try any hex like #ff0000 or whatever combination I put it is always grey (see below in the screenshot)
![image](https://user-images.githubusercontent.com/278367/153478173-a41289e7-c2e7-4600-ad73-4e728e737210.png)

**Comment by sudhamsugurijala** [comment] 2022-02-17 08:17
Hi

I tried to reproduce the issue, but looks like hex color code is working fine.
![image](https://user-images.githubusercontent.com/54114483/154433801-9fd961fb-7149-40d8-a57a-3aee09dc9961.png)

**Comment by EmidioStani** [comment] 2022-02-17 12:43
Thanks for checking this, I wonder what the problem would be

**Comment by joshinils** [comment] 2022-03-03 02:24
this should print various colors randomly
``` python3
#!/usr/bin/env python3
import tqdm
import time
import random


def hsv_to_rgb(h, s, v):
    c = v * s
    x = c * (1 - abs((h / 60) % 2 - 1))
    m = v - c

    if 0 <= h < 60:
        r, g, b = c, x, 0
    elif 60 <= h < 120:
        r, g, b = x, c, 0
    elif 120 <= h < 180:
        r, g, b = 0, c, x
    elif 180 <= h < 240:
        r, g, b = 0, x, c
    elif 240 <= h < 300:
        r, g, b = x, 0, c
    else:
        r, g, b = c, 0, x

    return f"#{hex(int((r+m)*255))[2:].rjust(2,'0')}{hex(int((g+m)*255))[2:].rjust(2,'0')}{hex(int((b+m)*255))[2:].rjust(2,'0')}"


while True:
    total = 360
    pbar = tqdm.tqdm(total=total)
    s, v = random.random(), random.random()
    for h in range(total):
        pbar.update()
        pbar.colour = hsv_to_rgb(h, s, v)
        pbar.refresh()
        time.sleep(1 / total)
```

my system info;
```
4.60.0 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] linux
```
and info for `code --version`
```
1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64
```

but i did have some issues with this skipping lines up and down, and even a runtime error:
```
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:03<00:00, 114.02it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:02<00:00, 176.39it/s]
Exception in thread Thread-1:█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:01<00:00, 323.08it/s]
Traceback (most recent call last):████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:01<00:00, 324.86it/s]
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:01<00:00, 322.13it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:01<00:00, 323.49it/s    self.run()████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 299/360 [00:00<00:00, 322.75it/s]
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/_monitor.py", line 69, in run
    instances = self.get_instances()
  File "/home/niels/.local/lib/python3.8/site-packages/tqdm/_monitor.py", line 49, in get_instances
    return [i for i in self.tqdm_cls._instances.copy()
  File "/usr/lib/python3.8/_weakrefset.py", line 92, in copy
    return self.__class__(self)
  File "/usr/lib/python3.8/_weakrefset.py", line 50, in __init__
    self.update(data)
  File "/usr/lib/python3.8/_weakrefset.py", line 119, in update
    for element in other:
  File "/usr/lib/python3.8/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

**Comment by sudhamsugurijala** [comment] 2022-03-04 06:39
Hi @joshinils
I added `pbar.close()` after the for loop and put `pbar.update()` after setting `pbar.colour` as shown below:

```
#!/usr/bin/env python3
import tqdm, time, random, colorsys

def hsv_to_rgb(h, s, v):
    r, g, b = colorsys.hsv_to_rgb(h, s, v)
    return f"#{hex(int(r*255))[2:].rjust(2,'0')}{hex(int(g*255))[2:].rjust(2,'0')}{hex(int(b*255))[2:].rjust(2,'0')}"

while True:
    total = 360
    pbar = tqdm.tqdm(total=total)
    s, v = random.random(), random.random()
    for h in range(total):
        pbar.colour = hsv_to_rgb(h / total, s, v) # Changed 360 to total
        pbar.update()
        pbar.refresh()
        time.sleep(1 / total)
    pbar.close()

```

The bars kept changing colours (not captured by this picture) and i got an output with no errors - 

![tqdm-snip](https://user-images.githubusercontent.com/54114483/156712346-d4f9cdd8-3925-48b4-a018-e22a94c7ff19.PNG)

Was this the intended output?

I cloned this tqdm repository and checked your code. I hope it is the same with the standard pip tqdm installation.

**Comment by joshinils** [comment] 2022-03-05 00:00
> I added pbar.close() after the for loop and put pbar.update() after setting pbar.colour as shown below:

Aha, I forgot `close()`, that indeed was the issue.
> The bars kept changing colours (not captured by this picture) and i got an output with no errors
> Was this the intended output?

Yes, I wanted it to loop through as many colours as possible, so each bar goes through all hues with random saturation and value, but I guess that's not necessary to check for colour support.
> I cloned this tqdm repository and checked your code. I hope it is the same with the standard pip tqdm installation.

I am using the standard pip install

**Comment by casperdcl** [comment] 2022-06-18 10:40
Closing this as it doesn't seem to be reproducible.

**Closed by casperdcl** 2022-06-18 10:40 UTC
Labels: invalid ⛔, p2-bug-warning ⚠

**Comment by casperdcl** [comment] 2022-06-18 10:43
Also since [v4.63.2](https://tqdm.github.io/releases/#v4632-2022-04-04) (thanks to #1309) you should be able to use the notebook version in VSCode (`tqdm.auto`/`tqdm.notebook`)
