### ISSUE TITLE
Running pandas df.progress_apply in notebook run under vscode generates 'dataframe object has no attribute _is_builtin_func'

### ISSUE THREAD

**Issue by dickreuter** [tqdm/tqdm#1202] opened 2021-07-05 23:03 UTC
Code Sample, a copy-pastable example
df['col'].progress_apply(lambda x: x+1)

Problem description
generates an error message when run in notebook under vscode (but works fine when run in a normal jupyter notebook)
dataframe object has no attribute _is_builtin_func

Expected Output
Should show a progress bar and perform the apply lambda

Output of pd.show_versions()
1.3.0

**Comment by casperdcl** [comment] 2021-07-06 06:38
Duplicate of #1199

**Closed** 2021-07-06 06:38 UTC
