### ISSUE TITLE
pb.write and print don't work in jupyter notebook

### ISSUE THREAD

**Issue by KOLANICH** [tqdm/tqdm#644] opened 2018-11-23 10:11 UTC
The version used is 350640d3171a568fb3f22d64d898e154541acc56
Neither
```python
with tqdm(...) as pb:
    pb.write("test")
```
nor

```
with tqdm(...) as pb:
     print("test")
```

work.
It turned out that the text output is buffered somehow, and flushed only if there are lot of lines. It is not flushed even on cell execution finish.

**Comment by casperdcl** [comment] 2018-11-25 10:19
that's odd. if that's jupyter's decision then I'm not sure if we should try to forcefully `flush`...

**Comment by KOLANICH** [comment] 2018-11-25 12:11
>that's jupyter's decision then I'm not sure if we should try to forcefully flush...

I have tried, it doesn't work.

**Comment by chengs** [comment] 2018-11-27 12:50
let me have a look

**Comment by KOLANICH** [comment] 2018-12-02 08:13
BTW, in jupyterlab without widgets module installed the output works. I have not tested with widgets installed, because in jupyterlab widgets are npm module, not python one.

**Comment by chengs** [comment] 2021-11-16 09:55
Closed as the problem is fixed.

**Closed by chengs** 2021-11-16 09:55 UTC
Labels: to-fix ⌛, p2-bug-warning ⚠
